---
keys:
  - users:
      - &ramblurr 978C4D08058BA26EB97CB51820782DBCACFAACDA
      - &disaster-recovery age15j42dspmmwprjau6l48xp05d97s8ml5s3tjxrfwvm37tvuynssuqtsevkj
  - hosts:
      - &quine age1catrh86sctuqvec04nhxwsmm7cpem4mx62smt3upt0480d6fve5q4gtx42
      - &mali age10w46rzpkfyx7cfx8hy6dq059cw8zy7mrvtu2gc06hngyxspeh9aq45ssty
      - &debord age1ns0hnk5n6sw9uqdn7v4rynumjk0zd8zfsjhegka74xw55nnluy4qtju5um
      - &dewey age1dtwmd5txsdjh3agr7zlqum8h024hasarflnpfavyqsu7g2lvvyksv8zff5
      - &witt age1dzr2v5py0vwj3wujdmfgcfjqc26vz07u7vl0j8la345y97f0au2smk79jd
      - &addams age1t70vans0qsnru7j06fwtj7wq7hpfj59cxreu9a20rrxuahff9fmqsa2wjd
creation_rules:
  - path_regex: terraform/secrets.sops.ya?ml$
    key_groups:
      - age:
          - *quine
          - *disaster-recovery
        pgp:
          - *ramblurr
  - path_regex: secrets/secrets.sops.ya?ml$
    key_groups:
      - age:
          - *quine
          - *disaster-recovery
        pgp:
          - *ramblurr
  - path_regex: hosts/quine/secrets.sops.ya?ml$
    key_groups:
      - age:
          - *quine
          - *disaster-recovery
        pgp:
          - *ramblurr
  - path_regex: hosts/witt/secrets.sops.ya?ml$
    key_groups:
      - age:
          - *witt
          - *disaster-recovery
        pgp:
          - *ramblurr
  - path_regex: hosts/mali/.*.sops.*$
    key_groups:
      - age:
          - *mali
          - *disaster-recovery
        pgp:
          - *ramblurr
  - path_regex: hosts/debord/.*.sops.*$
    key_groups:
      - age:
          - *debord
          - *disaster-recovery
        pgp:
          - *ramblurr

  - path_regex: hosts/dewey/.*.sops.*$
    key_groups:
      - age:
          - *dewey
          - *disaster-recovery
        pgp:
          - *ramblurr

  - path_regex: hosts/addams/.*.sops.*$
    key_groups:
      - age:
          - *addams
          - *disaster-recovery
        pgp:
          - *ramblurr

  - path_regex: configs/home-ops/.*.sops.*$
    key_groups:
      - age: &all-nodes
          - *dewey
          - *debord
          - *disaster-recovery
        pgp:
          - *ramblurr
