---
keys:
  - users:
      - &ramblurr 978C4D08058BA26EB97CB51820782DBCACFAACDA
      - &disaster-recovery age15j42dspmmwprjau6l48xp05d97s8ml5s3tjxrfwvm37tvuynssuqtsevkj
  - hosts:
      - &quine age1catrh86sctuqvec04nhxwsmm7cpem4mx62smt3upt0480d6fve5q4gtx42
      - &mali age10w46rzpkfyx7cfx8hy6dq059cw8zy7mrvtu2gc06hngyxspeh9aq45ssty
      - &ovos-kitchen age1vfgnjj357pa8xq0vpl9cnfxhtczl7dgnafxlqal3pn9v4ud0kees4xua20
      - &ovos-bedroom age12zdskqd632afljf4nffxafup4mhd0kl53psvqer8zup8qz9gn3qqtp7858
      - &vpn age1fejrfw2c8z8g02z6j9fv4ddwm7y4valtmstxmpl0yktk7dm49phspxglgf
      - &ibnsina age1rd4msy9hc7t7703kwypmt20r8qwkuqxyxuk3sd95sw2sc9gvjydqe67dn2
      - &k3s-test age1j4ga2thelk9t42s6shaeuen0pst32dcx9lyu9rzsq2qacnuchdsq80tvey
creation_rules:
  - path_regex: secrets/secrets.sops.ya?ml$
    key_groups:
      - age:
          - *quine
          - *disaster-recovery
        pgp:
          - *ramblurr
  - path_regex: hosts/unstable/x86_64-linux/quine/secrets.sops.ya?ml$
    key_groups:
      - age:
          - *quine
          - *disaster-recovery
        pgp:
          - *ramblurr
  - path_regex: hosts/stable/x86_64-linux/mali/.*.sops.*$
    key_groups:
      - age:
          - *mali
          - *disaster-recovery
        pgp:
          - *ramblurr
  - path_regex: hosts/stable/x86_64-linux/ibnsina/.*.sops.*$
    key_groups:
      - age:
          - *ibnsina
          - *disaster-recovery
        pgp:
          - *ramblurr

  - path_regex: hosts/stable/x86_64-linux/k3s-test[0-9]+/.*.sops.*$
    key_groups:
      - age:
          - *k3s-test
          - *disaster-recovery
        pgp:
          - *ramblurr
  - path_regex: hosts/stable/x86_64-linux/vpn/.*.sops.*$
    key_groups:
      - age:
          - *vpn
          - *disaster-recovery
        pgp:
          - *ramblurr

  - path_regex: hosts/unstable/aarch64-linux/ovos-kitchen/.*.sops.*$
    key_groups:
      - age:
          - *ovos-kitchen
          - *disaster-recovery
        pgp:
          - *ramblurr

  - path_regex: hosts/unstable/aarch64-linux/ovos-bedroom/.*.sops.*$
    key_groups:
      - age:
          - *ovos-bedroom
          - *disaster-recovery
        pgp:
          - *ramblurr
