---
version: "3"

#env:

includes:

tasks:
  default:
    silent: true
    cmds:
      - task -l

  check:
    cmds:
      - nix flake check --all-systems

  update:
    desc: Update all the flake inputs
    cmds:
      - nix flake update

  update:input:
    desc: Update a specific flake input (e.g., task update:input input=nixpkgs)
    vars:
      input: '{{ or .input (fail "Flake input name `input` is required") }}'
    cmds:
      - nix flake lock --update-input {{.input}}

  nixos-rebuild:
    internal: true
    cmds:
      - nixos-rebuild --fast --use-remote-sudo --build-host {{.BUILD_HOST}} --target-host {{.TARGET_HOST}} --flake {{.FLAKE_URI}} {{.ACTION}}

  switch:quine:
    desc: Switch quine
    cmds:
      - sudo nixos-rebuild --flake  .#quine switch

  build:quine:
    desc: Build quine
    cmds:
      - sudo nixos-rebuild --flake  .#quine build

  test:quine:
    desc: Test quine
    cmds:
      - sudo nixos-rebuild --flake  .#quine test
  test:mali:
    desc: Test mali
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: test
          BUILD_HOST: mali.int.***REMOVED***
          TARGET_HOST: mali.int.***REMOVED***
          FLAKE_URI: .#mali
  build:mali:
    desc: Build mali
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: build
          BUILD_HOST: mali.int.***REMOVED***
          TARGET_HOST: mali.int.***REMOVED***
          FLAKE_URI: .#mali

  switch:mali:
    desc: Switch mali
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: switch
          BUILD_HOST: mali.int.***REMOVED***
          TARGET_HOST: mali.int.***REMOVED***
          FLAKE_URI: .#mali

  test:ovos-kitchen:
    desc: Test ovos-kitchen
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: test
          BUILD_HOST: ovos-kitchen.int.***REMOVED***
          TARGET_HOST: ovos-kitchen.int.***REMOVED***
          FLAKE_URI: .#ovos-kitchen
  build:ovos-kitchen:
    desc: Build ovos-kitchen
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: build
          BUILD_HOST: ovos-kitchen.int.***REMOVED***
          TARGET_HOST: ovos-kitchen.int.***REMOVED***
          FLAKE_URI: .#ovos-kitchen

  switch:ovos-kitchen:
    desc: Switch ovos-kitchen
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: switch
          BUILD_HOST: ovos-kitchen.int.***REMOVED***
          TARGET_HOST: ovos-kitchen.int.***REMOVED***
          FLAKE_URI: .#ovos-kitchen

  image:ovos-kitchen:
    desc: Build the SD Card image for ovos-kitchen
    cmds:
      - nix build .#images.ovos-kitchen

  test:ovos-kitchen-sat:
    desc: Test ovos-kitchen-sat
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: test
          BUILD_HOST: ovos-kitchen-sat.int.***REMOVED***
          TARGET_HOST: ovos-kitchen-sat.int.***REMOVED***
          FLAKE_URI: .#ovos-kitchen-sat
  build:ovos-kitchen-sat:
    desc: Build ovos-kitchen-sat
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: build
          BUILD_HOST: ovos-kitchen-sat.int.***REMOVED***
          TARGET_HOST: ovos-kitchen-sat.int.***REMOVED***
          FLAKE_URI: .#ovos-kitchen-sat

  switch:ovos-kitchen-sat:
    desc: Switch ovos-kitchen-sat
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: switch
          BUILD_HOST: ovos-kitchen-sat.int.***REMOVED***
          TARGET_HOST: ovos-kitchen-sat.int.***REMOVED***
          FLAKE_URI: .#ovos-kitchen-sat

  image:ovos-kitchen-sat:
    desc: Build the SD Card image for ovos-kitchen-sat
    cmds:
      - nix build .#images.ovos-kitchen-sat
