---
version: "3"

#env:

includes:

tasks:
  default:
    silent: true
    cmds:
      - task -l

  check:
    cmds:
      - nix flake check --all-systems

  update:
    desc: Update the flake inputs
    cmds:
      - nix flake update

  nixos-rebuild:
    internal: true
    cmds:
      - nixos-rebuild --fast --use-remote-sudo --build-host {{.BUILD_HOST}} --target-host {{.TARGET_HOST}} --flake {{.FLAKE_URI}} {{.ACTION}}

  switch:quine:
    desc: Switch quine
    cmds:
      - sudo nixos-rebuild --flake  .#quine switch

  build:quine:
    desc: Build quine
    cmds:
      - sudo nixos-rebuild --flake  .#quine build

  test:quine:
    desc: Test quine
    cmds:
      - sudo nixos-rebuild --flake  .#quine test
  test:mali:
    desc: Test mali
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: test
          BUILD_HOST: mali.int.socozy.casa
          TARGET_HOST: mali.int.socozy.casa
          FLAKE_URI: .#mali
  build:mali:
    desc: Build mali
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: build
          BUILD_HOST: mali.int.socozy.casa
          TARGET_HOST: mali.int.socozy.casa
          FLAKE_URI: .#mali

  switch:mali:
    desc: Switch  mali
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: switch
          BUILD_HOST: mali.int.socozy.casa
          TARGET_HOST: mali.int.socozy.casa
          FLAKE_URI: .#mali

  test:kitchen-ovos-satellite:
    desc: Test kitchen-ovos-satellite
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: test
          BUILD_HOST: kitchen-ovos-satellite.int.socozy.casa
          TARGET_HOST: kitchen-ovos-satellite.int.socozy.casa
          FLAKE_URI: .#kitchen-ovos-satellite
  build:kitchen-ovos-satellite:
    desc: Build kitchen-ovos-satellite
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: build
          BUILD_HOST: kitchen-ovos-satellite.int.socozy.casa
          TARGET_HOST: kitchen-ovos-satellite.int.socozy.casa
          FLAKE_URI: .#kitchen-ovos-satellite

  switch:kitchen-ovos-satellite:
    desc: Switch  kitchen-ovos-satellite
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: switch
          BUILD_HOST: kitchen-ovos-satellite.int.socozy.casa
          TARGET_HOST: kitchen-ovos-satellite.int.socozy.casa
          FLAKE_URI: .#kitchen-ovos-satellite

  build:rpizero2:
    desc: Build the SD Card image for an rpi zero 2
