---
version: "3"

#env:

includes:

tasks:
  default:
    silent: true
    cmds:
      - task -l

  check:
    cmds:
      - nix flake check --all-systems

  update:
    desc: Update all the flake inputs
    cmds:
      - nix flake update

  update:input:
    desc: Update a specific flake input (e.g., task update:input input=nixpkgs)
    vars:
      input: '{{ or .input (fail "Flake input name `input` is required") }}'
    cmds:
      - nix flake lock --update-input {{.input}}

  nixos-rebuild:
    internal: true
    cmds:
      - nixos-rebuild --fast --use-remote-sudo --build-host {{.BUILD_HOST}} --target-host {{.TARGET_HOST}} --flake {{.FLAKE_URI}} {{.ACTION}}

  nixos-rebuild-local:
    internal: true
    cmds:
      - nixos-rebuild --fast --use-remote-sudo  --target-host {{.TARGET_HOST}} --flake {{.FLAKE_URI}} {{.ACTION}}

  switch:quine:
    desc: Switch quine
    cmds:
      - sudo nixos-rebuild --flake  .#quine switch

  build:quine:
    desc: Build quine
    cmds:
      - sudo nixos-rebuild --flake  .#quine build

  test:quine:
    desc: Test quine
    cmds:
      - sudo nixos-rebuild --flake  .#quine test
  test:mali:
    desc: Test mali
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: test
          BUILD_HOST: mali.int.socozy.casa
          TARGET_HOST: mali.int.socozy.casa
          FLAKE_URI: .#mali
  build:mali:
    desc: Build mali
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: build
          BUILD_HOST: mali.int.socozy.casa
          TARGET_HOST: mali.int.socozy.casa
          FLAKE_URI: .#mali

  switch:mali:
    desc: Switch mali
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: switch
          BUILD_HOST: mali.int.socozy.casa
          TARGET_HOST: mali.int.socozy.casa
          FLAKE_URI: .#mali

  test:ovos-kitchen:
    desc: Test ovos-kitchen
    cmds:
      - task: nixos-rebuild-local
        vars:
          ACTION: test
          TARGET_HOST: ovos@ovos-kitchen.int.socozy.casa
          FLAKE_URI: .#ovos-kitchen

  build:ovos-kitchen:
    desc: Build ovos-kitchen-local
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: build
          TARGET_HOST: ovos-kitchen.int.socozy.casa
          FLAKE_URI: .#ovos-kitchen

  switch:ovos-kitchen:
    desc: Switch ovos-kitchen
    cmds:
      - task: nixos-rebuild-local
        vars:
          ACTION: switch
          TARGET_HOST: ovos-kitchen.int.socozy.casa
          FLAKE_URI: .#ovos-kitchen

  image:ovos-kitchen:
    desc: Build the SD Card image for ovos-kitchen
    cmds:
      - nix build .#images.ovos-kitchen

  test:ovos-bedroom:
    desc: Test ovos-bedroom
    cmds:
      - task: nixos-rebuild-local
        vars:
          ACTION: test
          TARGET_HOST: ovos-bedroom.int.socozy.casa
          FLAKE_URI: .#ovos-bedroom
  build:ovos-bedroom:
    desc: Build ovos-bedroom
    cmds:
      - task: nixos-rebuild-local
        vars:
          ACTION: build
          TARGET_HOST: ovos-bedroom.int.socozy.casa
          FLAKE_URI: .#ovos-bedroom

  switch:ovos-bedroom:
    desc: Switch ovos-bedroom
    cmds:
      - task: nixos-rebuild-local
        vars:
          ACTION: switch
          TARGET_HOST: ovos-bedroom.int.socozy.casa
          FLAKE_URI: .#ovos-bedroom

  image:ovos-bedroom:
    desc: Build the SD Card image for ovos-bedroom
    cmds:
      - nix build .#images.ovos-bedroom
