registrationSharedSecret: ENC[AES256_GCM,data:tsMzCecqnZBhXGtIEEDXvTXIFvAdSQsIvw63AKrYtyfhAo/VXSW2dPWzBaggbs8ckaN3gpIkqJDvSjCZp5ZOkQ==,iv:gNQRsw3PV+nBW6R5V1Qlu9ktd7myNv+qjbPAVKxMc9k=,tag:c9El7Wk/1PRgj+e+RfyUtQ==,type:str]
signingKey: ENC[AES256_GCM,data:KzEz4nLf++8XqmNAjriIQLVkj2J6QXDPdSh987jEDWOCqjp4t+X6l7xSqoCXDrbmmdlELAVACeoHmR4=,iv:IHeWS8HUKgoHEkNLuRkkjRZ/A7ZjGQ3UWpvfSauoJfI=,tag:9Y8djQgrI9vFi5iEMs8vng==,type:str]
doublepuppet-as-token: ENC[AES256_GCM,data:Xm13j5uxpjLvvVxVmrC2aDq0kyH0q2jDShk+WjR+smobmWUJT3DbJ5NqFz2F8le3,iv:VRk3Gd+sb22RFoYZ4Rc3+xIF1c1v9EnuOcIuoBVKoDw=,tag:ss2gAZxHuNUgnaBEUQJqKA==,type:str]
doublepuppet-hs-token: ENC[AES256_GCM,data:vXPtgycHka0dNiUrTDI23ixS72hv+8hnKrun/Pt03gcR80iflnSwueKS6esIDxEc,iv:FpDZ/M54nfgMY8Q7NwCKQrFC1c2dVTl5VScJV/JSsvk=,tag:Ns/MMzhmlOF/U8aVdyZeRA==,type:str]
mautrix-discord-as-token: ENC[AES256_GCM,data:mqjz8pxcWPbaQ1oz7Z6MBxM0FDqURO5xr784vOBigdicDO+4THJE6YDBrWybB+3yDxA9fGuorlMlx+YEierMnQ==,iv:O3pXOMBldOfYWGnK9RtLljmbyYqFfmRZrtXmWdnFMrg=,tag:7IomWk2jOUpd1lNrXlgAeQ==,type:str]
mautrix-discord-hs-token: ENC[AES256_GCM,data:fGoxP1WhhSxcFVl/VGGyuPUww0rZjoVrvgrwwVmkVLiUn9XEnKNqp1eXpr1uayzI7SiwJGm7jlvg2FXTa+qluA==,iv:GGoxTL9VmFaGvV4vr0qMv/5w+o7AWnR4td8KHEXX0mo=,tag:/caIbKS3w3N6+a9cN63rxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDR0TFMwUSBBMDU2ZUxX
            dEFNSVZzeEN6OHEwM1A5U3Z5T21Zd1E2OVhSSTRrb3RHSEx4dwpDK1lYdUdwREFN
            N3F5cnhXWjM5WVVSVVdid1p2RFVGQ2wxc1BkTk1YL1U0Ci0tLSBsTFVhcEtMa1N6
            ZmZLWUVBVkx0OFNvSTQvd1FyY0tzM0orU09jVmk2ZEswChibz+nTYsmMnMIJou3a
            b0+jM4v+VjejV9EAyy4nB+WFH7mJylnqu3pRhE7La76Y5VocGUgDKSyGnfrLWTNq
            b+A=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qt0lmjdz8l27zy8gqlwu5hpplunz5dcsszuqjau7q7sdnksjqhm5cg2jkkl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDVlcW1kdyBBdVN1eVJv
            andCZHdrMmZrb0k4SitZNm5rcnRqSlBBcWZVSGNsb1orZVBvQgpHY0t6Y2RoZGph
            UDQ2cWxZWElSc3VRWWUzT0ttdTFuYTZnSUtxUjhsSTl3Ci0tLSArbE1ySjdCaTBL
            TlNieHVkanNjL1MvLzYweUx4dzk5TUN2emtWWk9oeGY0CssQapP/3oaVcWj3MhdS
            L0btB0hTeDYubzY/eGsYnpp+NmER1WyhRfYaOS7l1lIt8kAH/NKA8Ygqxq5INElm
            6Cs=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvm060q3kense6l22nrjd5a9gqsm9k4eaanhuk5h3hpmvzes8xd6584fsvn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGFtV2Z1Vllz
            QUtFOVVUdE5DRVVXQysxZEdvVU1GVHJvT1NoY1BQSk5ONHZyMmlMd1BnWVBPVXp1
            Um1CZnlycjVNUm9wZ2JOSmxmaFNMNVZFSHB3NWNSZnBJS3duMzNxZElVcTJYOXNm
            S2tMcUlCNzc2NmVzbnRtN2NLdktaUjVBQW5tRWkwUHhPNVhGelltWFN2VXFHRmlB
            anlPTlNnc3ZRSTBXaElkOElHMDdaVXFBY0ZCaE1nSVVLdFpWNDdidjJFT2VaWGcz
            UTFQTmZlUCtWc0xjSFBHWUU4NXV3a2NkVmhaWnJSc2JmZkZLSFV0T1J3VWlVdXJO
            SmJIMUk0OXZhbDE4MHhQVXFmZllsUUlMalhkd2c1YnRtTmNnVmxTUzFONExreXJ4
            S2RxMDdOMHFPTENGTkJsVlplZlpMTGRRSHZDSWVRZHVpOW9UYTE2T1VTc2xCcE9p
            NW1vNHVRdWF0aWFjWEppaFNnaTBFWVhvSVY5Z1BVOFVBM1p0TWl1UHV3dDJsSklF
            dkJiMVlIQlExNTdybDlLdDd2YXdxdHNVT1g3MXB4OE9LWXltcTQwcG1FbzQrOUs0
            c0VDZjRESkwzbFRsUktPU29FL2ZMVTltanNlWE9UQ0JUcWV3ZzI4U1ljWHVNOHFP
            ejRORWxyUVZxd0hYa0dlQ2lobEF2YXFqL21kcjJPeXlibTdhY2JTaWZCT3dPWUdp
            RzlmSnZzZm9yYitucjg5dWtFL3JmWDlPSlh4VVZNN3B3Q3k0NnZpVHZjY09wUFdw
            OTlKdVQ5czRHQlhKcEFucmIySVFLOWwxaE9KQ0NoWXJTZXJaeVV0VEZFVGd0aVB5
            cE5hZFhJRnR5L1dZWVphNkpmM2lBUUZRRHhBMFlDNEszSHc5cDVNTDhoNENnNlFI
            SlNKNHJsMGxMQ09GRzJOVHBRVjhSTWI3akZDNU1JaXo2dXRqSkx6aXo4YS96TW5s
            RGx6M0o0U2E2bkFtaHgwTXdrWk5td3NDa0NlUDdCUG1nLzMrTDlUZEl6OHRDcUFa
            cVh0QUh3Zi9HeXo1T1d0ZXd6RTMxMmZhdHk5c0xkZnZtc0huRVdYUDBoMkZaOEM4
            UGhSaTV5Nlg0MEhKUWtPckx3Wlc5ZGNRRHQ4REM1ZDF0WEZUM1BtRzRVcTlVY0xt
            cnA1OERIUmRRM3VFSUlXMzRSVDJwRUlNV3liSFF2aGFVQ25pY0FjMDVaU1YrSTEz
            QzFUK0taK0xjSVJmTDk0SEYrMTdGU2g4Q0h6cE9DNEh2TEdCWkc3ZG13NmM0TXdO
            T21mUFZVRUovbE8vdXBGbEIvblhvd25SdEhKTXE3WElPbmJqb3RrVXNQa1plU1N1
            WGc5T3FyMDl0TjNvUk91M1VFaHN3bUo1ODBLcm0vTFpBc2JNMGNGd1VXa2VDTmlJ
            VEZsRklodnRhYVY5UHc1Z3k3d1pMUVdpdFl2b01XWWtWYWFBb0R3YmRhZDUyNldL
            Y3c4elJ2UERYTWttUlFxVkovWklxUlJpbTAvQklPTXlXcG9QSjQ5ano1TWVlbTEw
            TkFMNlNPMmNjUU4rU1Vzb1c5V0Y5SUtIOEt4U094Y3lkeU1CUEtiRTJBWGZFdXYy
            cTZVTnRLbm5oK2F1a1pBMDRCTXB0WHJXcWFla3ZzZGV3WnJhL08reE5CY0M5ajZk
            ckIyZDJDR0NzSDlUbWxVTmF0bitTdVBUSVNETXY4am9CcHRpQUFOUzBrTVpQM3pn
            TDhYSnJYWHdzak04ZE9pK1JBc3lQR2RHRklQWENFQXFDTG9oVFN3eTdQMnJRb2w0
            QTlORUk1c21sd1o2OFhmVVhvTTRQbzFGaENtaE5Xb0hoZjJYcjRwV0pvN1g1bzgz
            Ky9IMHhKYkhGT1RjbVY2b0xyMjhmUHlkYjBhb0NhSDNMaTNiN0cva2JzL253MlFa
            TUsyZWdYMWxNUEo2bzY0dktZZ2FGeDBUeUYvSFRIQW5Ub1lic283M1RRcFNiQQpG
            L1VMOE15Nk83WTd6OXQzWnZsUTFoT3BsZGROV0MweVNubzJFV1BjWXhjCi0tLSBU
            bmlEcjI3bTB4b2gyQnliZXpwWEFLQy90TnN3dDltdjZPVTVCV3lSTnFBCi1rzjQu
            Fmf1R6VQ2BYBpWaUnH5YiTvC7BFh5qVI3Zxmu1OgwPKLqUw70Ly/VbRVqRYH89Wp
            /7PiE/BGv6KL6rQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1txa5jfq4y6xn2w6aj778jkyu8wsm47ke0pt05jm4dgmhj7chenqcnr0rq47y2sm4kacyp49w9wcyyc7z29luwrlvjcd0y7n7urnjkvheqx3nyl0xpvvwhdw0vkahpd5e9c8ctn7ej68y93z56eq4tw0cg92425tsmrr4t3frkwkyrv2t59ldwnsscwhqwqxtyv6q6gvrfj2trrclscvjd4plcsrtj8vhq9cc0f0sujwd5vuum59rnaxc4se0sh9uq223ln9n0hyt29m3578he24urp625k6wnmgkgmsncnamccy48wleaxzqrsnc463rstpgc7s3n3mu35457aasshr8n43s290f2s92kqps2n969h8g0djexymceqlqvq5ctrp68a9m5k0x5chxhqr7a7tr55n4r3wcynnwdyyehpxxp2ap25yt6hxqxkphtveyagd8wsa0dkah4mluj7nhd2ddlxne689h9euk6smsj8yfhda8kr8lw72vgjckwhzeeqxspxftgpuyr79q52ajdh0kz6duf2xlx4tr35z9ntfj3arzq4jehz0yjwrqwecsk4469x8p94ekswhfhp8mxagceaehgytvntn7nz6zeg832rp5vznmxndv5avc2ttlhgxuqvpssk4x3gl2xw80ksgz0gzru4d8gz3jlue82wtgk2pvhswle42ldecnrnx5klmhf0nsgywhkanzajpsg8dkgvf5yxgfjqeu5xn06vnmvepvfdkr5jand3ja3uz9axut35jvp85xjkrzlxtz5wvl29zqfkc8yxwujykx6v23njd33cufge9h0nt5400glvrfndd4hjfvvywh8rlq39lwl9f5yuc66n4v2ufzq0sgzrnmtz92dstfv93f59ymt5a33ds8kxst5997teu5hj8tqwuzk73z5wepcgsqys9ql7sjn5p9z9l2xft8s5zryrz6sstvxuj34p9jm36vsy5sj3z3ec7q8sg4chkeddy43qkqcaf5ave58xq40zngh9y55vjz7du4dtfcddxatwtm3p6pzxpepftqd8pkjmmughhxhdq7e6pealyv9gj6w5ps2tqx24kk7l9kl3zjlemvkvk38qgfva4wfpnjemjfjdjyzmc2sn88e3afz6553gstpffm0uu7d3gfwwm72fd7ezx9sxhffdrrnvymuknugepms79m6pyhjyp7ye366jrp59da07ufgcc6kyfdx26mgnqq74cdzqdr824vzx0vdff0gm8mnpudgmfxnz4r5yue5pln54m0pw542858frvhr30v5xt77cqh0qa29anyt7xuhchx40pf6d7mcz44nerpn5qq4g35qc7ad9kyma5uwrqenythpa7txkns5e5lu8yhuumnlu88yv8zssm5npku5af08tasfmy8kpm483jyddzkeve7asqsxw6x00ra3wg7rqhzu5zr8pykcf03c8cu3w48t2sd72wzffsky93pkwfw3jnmuc78me6t7hfg08ruxnp5xwz56q4f7evl6zuukgnxfrpqyk4aqaq0f7rdhlrfphume8tftsgn8ynjt7rgsgfgas5spn3s4nzrgp7ajurfj678h0d60p3l48e62eeps7q5n6m6n5mxw7mdr9a3sckkah9lctv33zfzvt48v4m4wjxqpywvgcdqs4cx9fedzm8klzkvussp5emv9zv4g3v68tgvfp57ap335kf8sq58h93e3tghudem0vzerqts5pxfel59k5gftsr4cxempk98uumjjdyc8pcwljflyftc6ne6a8lr4gumvtk77yyj9espzlskx5dz8prn38wn5xqfwy3xhjzx8xps5tdckxhaejy9mfjavjhrj68wwwzx809zgkckn63dsg2jqg85h3hnwnpw9rm8jy5udzd62ej52ycwkv7ejwsm6dr4zcavgsua
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN0sxbXJGSTB2UVRXQkxn
            UTdPUkk0a1JxcmEvd1pzRy9JSGl4cmVrMUNvClpLelZkTFgyL0x4Q3ZIeUtnb3dS
            a1hCZFdXME9SbEthRWxzMEdlN3lSeGcKLS0tIFo3bHZwdEhxTzBhdmI5SmhEU2NW
            TktLOUlKYzQ5c2NYQ2xNOG5BaXg3TEEK/fMHLhEjMWhlAvR3ih5WBNUo6EjZ+g6M
            f8jRPEF73OsyLxl8L2k+h8HyiER0virgpp6Gn8/Z7eEZFqOf0My+4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dtwmd5txsdjh3agr7zlqum8h024hasarflnpfavyqsu7g2lvvyksv8zff5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRkJjNHlxOXg3d1p2NzBR
            UXM1VVBZem1TRXVEVk5iakh4U1VvVFFBQ3o4CjlwRGpvMVJGK3lkemRwdXNPSXVC
            VjVxTVFBU2JXcEFlQmpCRVdueG4zOGcKLS0tIHdmQlVvNWJnNHoxVHVPalpmY0dQ
            RURMQVJjU1RYRXVrczRRNXRiMDJGV2cKky/WAejy48LoJEn/MZehWGSs8adNMwCp
            CqU+/NiFXPkZD24YsVoxDm0aChQf8eleudWNFeNA0ZjVfL4lLnyYuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ns0hnk5n6sw9uqdn7v4rynumjk0zd8zfsjhegka74xw55nnluy4qtju5um
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdW9pMi8wS2lDSzl2anhG
            SS9FeThOcm5vMXkrWVJLS01iZkM1WjBiZUhrCm54VzVlRjlJTEE0d2xsTmFHcnJp
            V3VuUDJoVHRTUVNGNlRwY3dNTWM2N0kKLS0tIHozcmZaanlLWTNZbVY4T3B1YUxa
            dlJlbnpqR1hDN3lhRnViQm1Ec3VVYVEKfVfu/skOv/B/JPz6VmfhDD3UhzW+328G
            SCbbdxj5mNxXuyylPv13SjmZix/nhWqwVv5S9Rh7j5+MrtCWlO/TPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10w46rzpkfyx7cfx8hy6dq059cw8zy7mrvtu2gc06hngyxspeh9aq45ssty
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bXNOOVZXYXhodzJWSzRJ
            RXNxUEtRcUQxdGpWTHlJVHdBb1lTWGRLKzFvCkFSVUliRnRiejZCYkJzdm1BK0Vi
            dUZsbHJmZDhIYTBDZXVjSmh5QXRVZDgKLS0tIHVlOURBeVY5bmxyalhZME5UUlUv
            czg0SGRVbGErczJ3Y0NJR3UxRGFwRkUKw1ImBdac1LiRaWGSp3KwAR1rQQR+1h/J
            4+C+Ac+fJD3/kGsoxbIPSRh/fcPFeYc/kH1iAvt+BMCgs1OGfEbi3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f67pujrh0ejw4a0540wmjs6jhxwdpkyvw798nnm5c6smfgmw99yqs34n2s
    lastmodified: "2026-08-17T16:34:30Z"
    mac: ENC[AES256_GCM,data:dmJe8zF+SzXbr3YhDT/rgTHOteKzHW+N9vCU94SnbYLCgmWPElhFcKPe9sRYStkxUX1TzNsZjkBuF46aWeQtH227zvnKkXZG7GS2tZahQ5UOUprlTCsDKDIqUP3LawAnE/vmS1xndP5wlqLny+n3qbmm57bdu0YKbopdBNhJ71c=,iv:pxlRIGbD0KZBoaXkLLx9eUQgyIovA7z3AVr2XILa0MI=,tag:QndwKHvrdLqTgwNAla1S/w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
