signingKey: ENC[AES256_GCM,data:KzEz4nLf++8XqmNAjriIQLVkj2J6QXDPdSh987jEDWOCqjp4t+X6l7xSqoCXDrbmmdlELAVACeoHmR4=,iv:IHeWS8HUKgoHEkNLuRkkjRZ/A7ZjGQ3UWpvfSauoJfI=,tag:9Y8djQgrI9vFi5iEMs8vng==,type:str]
doublepuppet.yaml: ENC[AES256_GCM,data:+muTc0/IRwGSirzH23gWIrlg42wkHiEwA97i/Sb+5LpFYB51xZT2QAsk+L6Yoqy93K7I91+fTdeZfpI0CQk0foJzcQ3Zz3ek+9gThT5VTsEBidLSstnMlAGRFUNwBlGTflAYrFofoyCGsb38K+OnhFpRoY9NMMuLVvIcHwb8Jqm4+bj0wdiAVapxIEhghzguRUbUZgQPDVuqBXj1+ITRYyxw5rt6tYD1rcMfyCIaa0czoINk6P9S5Ho7bLfgGrXn18xm5PJBEn2lsbcF9XuROniNaN8xcTHfmJeE22JF6Q+R5ICLKYp9NsKMN1NWRv3Cvfthu6fAT61BM+/Zl3VxJxpe4NxFzUrY4/AorBWMaacV1nkh0pMbyGx8D90SANlfLXevTAXoPNkAbXm5NeIXO6VoG0j2UfMmYKCrY835sEjRpcJrR2hQmbelRw6DfUjAkAxMadJES2dZ/ZsRp+GDA28SOIdJC6irlIyyF6KwZQIc0t0XwV2Qn1u+9/NTKsunymG3oiugI3RWPMlDVGCm5d/9mrme+bjJrM8IWhdcD38uOzF43OnOhrsF5NaHlIJhziXzoYffhzcqO3+6eFK12XYUcQPRAfN0eShfIkrXkpvOJvrW6mJV4DWqh1bC9Y6jzkIUudXfpf1b6JqDB+F0hB0M5dzm0FVvdKqDWIwroV1hI5ZizM6QK+deoqywDqXblYeOCsmJ2sTtxlfgsKZCeZtnR5lAzcfaUN26uYHUsSO47Yk0V2sOXuOk+5+tCL5ot3mJtYXhM9NVDsEa/li3AtK7NmQzcLMILIgX89Xt3jEVqRZ+7+yCCTDJNEiAMeP43P4NnWtCDKY7YxOZl8IrDSQQjLMq5AzlWuk0wlMDkH64dzRzYhtB1lhW6TQ69u4KZ9FjEF84QBpn0oygT6satfk+UNOi8fUDP6bGVLEojHBd4aZJLPGFIqMa5t1eBmM1RgrUr9/Igw1Mv73pWcQA1tZJgfxOqQM04A/zezgMXBYhChAjEQpxvo7383G4pD1bwkTKd22b7LbQU5iwxKx2oPCQPwxWgsDSBW/ZILHZ+/lhA5/YtG+Ifj6aSXUtGG/Jg6ZQB8JmbNtblDz7oAP0DYE5EmF1zy/Eh6NA418/t3Ssldw+IX3fcWa/NcaNk7IdC+NeP5O4PrB7BAfTBPbn9sL04NCK4brEkxIDDnvib/QymZUrnkkhKBz2YoOnzSkr/E+Tmbvg8P7B3L0h+jb/kXFvULyTlyelcMNVGBrj8w/tZMO9w4seMHdFnUV3Iek5e/RwHRtvffcVKKVoZ1DevYf48hm3Pv0xtDtcdJ6RhsFDAaefSNYSq7zOZ4BBAYe0kDlRD15KX27D02zW9MLkLLpufzeYjza+S3Cya+EHnKpuGzY1huq4LADxjg6CbUaULLohKed4QLjbbq+y0+MY/6FQPN7AULPK,iv:RM2A/jV2fDy7KjbLvK5GP+RjgLloNo4Z1T1DMlY6sgE=,tag:mpnlsDDu29MzY7ETdoTPVA==,type:str]
mautrix-discord:
    registration.yaml: ENC[AES256_GCM,data:V7x25Py1waJgfBIgHzv2XXhSNFZ8XaPRY/TqE8vknYznYNQiIdenM+NOwtsin0QrqLtkmPqmWgfndLpViuvCfrr6usTShveJggrbTffZ7zJif1HQWo5NfYcxjTxUCb4zkmBeZKStbYzTTAd88waMu5zD7bvcE7RwSowKW0xWiagj/WlS+1+nw7IMnaMus8vGm/vV2gXMcVejMuNokKceD0b/y9JT9xPDJfhJcSQZcmSRn0XfITF8tbIVOYELHUK60CN/W0YS8tyt4QznGqoHEUbkDZWtnDdH8s2AqtJFkUk8znSlAGHk8J26/xRHbq6KFGvoHdRY/JZCavc9/lnpEj7SkiLUDbf6Wfcqa3s2z06Nl0oKXZJiQRTw2eMLABLgonH7dZwe95ezOwv2MsHiOAEQLgjyKYb628CKW4CyRypsib1Rp5eYqBGFW/Hx5b5MRoRG6h48Sauum3MBMYcRhn9PajYzLy6TIo8Cm/GY69QpbX90R6ofr2Tn929ynHLEHXfySdJ/r4sdp2h87LB67XQh4kN28dcY2gqr36MAmdFfGwqxKUD2ojBPIxLMNNhSLeTcwV3EkJ7+pvqRxlQF3KGd0AH7V++e6DG63geUSMrkYY6Cg4bhqOXbWf59g6UHIXXs1d3/8AebOkoKicng05e1,iv:89RiyG6wz0tYNqWC6nFo6gasz5Sm/VItia7sHXLQ/H0=,tag:PHr/rgswBXOmmL71fBGW3w==,type:str]
sops:
    age:
        - recipient: age1yubikey1qt0lmjdz8l27zy8gqlwu5hpplunz5dcsszuqjau7q7sdnksjqhm5cg2jkkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDR0TFMwUSBBb3IwUXFU
            WWhxMFVPdFRYelVYTGRuT3Y3WXBiVFRtM3BzY3l2amExaHRrSQp0RmtiVHZseTB2
            N1pDY0RQNUliaWRha2RqQzAyMTFWSHY4R3A5S2pDQ21VCi0tLSBXbHJieVRFY0pw
            SE9YekRSYjVQZHgyQi9LMWYyT0J1a2FvNm4za1VSaUtjCq579K1YxauBdpJFFxok
            QZcMDFRA/m3q8HeWWqj2Eue8Mg5x9kvP2+UCVpDyHInxqJwaSjldzAUwcvRE9kXf
            Ihk=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qvm060q3kense6l22nrjd5a9gqsm9k4eaanhuk5h3hpmvzes8xd6584fsvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDVlcW1kdyBBOHFVd1I2
            RzdWU3pYSVZ4S3Z3VlB3RHVoUGEwN2NQVXRNcnNnM2RraEU5MQpmK2J6TnB0SXZB
            TzBNWldaaS84ME02R3ZqUVJDVURMUFJ6bWYveW5ROTVzCi0tLSByWlRDR2pZRUt3
            V1JPaDE5OTVYN0ZLdk03c1pOV29rZlZHV1J5NzBRRm9VCkY7cF3hFbgOjXfiOmcz
            z3bUM5gBpz19jP+NbJoln6bdqpa9Cej8XiUWZvPkBGPXDzBESPGGSdeW2w7GOH1t
            nr0=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15j42dspmmwprjau6l48xp05d97s8ml5s3tjxrfwvm37tvuynssuqtsevkj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqK3JPcTNMbDErelhDRVh0
            UVpRN0dqckFTQ2EySmNlMTJIdWxmcTlaT1hBClJ3NERsQ0FtTzdVeDNhNUMwQnBk
            OTNzaVVJSVB1WW5aMXVVWnNXU21OVFkKLS0tIGNhcXNjMGk4ZnRnMlorU09hTUhE
            VGdodVE5MCtram9Eam5hSVNRNEYwZk0K8rJ2Tc02BE5OSI3O1TtRNzI/+BkemX5P
            qkRWj9lvc1lDLvhomeOV6tcqe0WdtGHC3d54ZPTINH35FwqKPx7pXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dtwmd5txsdjh3agr7zlqum8h024hasarflnpfavyqsu7g2lvvyksv8zff5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdDlYODdLTjRIWFo5UXNL
            S21MTDFNMk04ekdJZ0FGV1NqeHl2eW1OM0hNCmlrWDUxUzlsNVhpc1RMMUdyMWhz
            ZVdqMG5yMFN0K2NKZExtOTltYUZJYkEKLS0tIDFaaUdKc0lxMTlQbENsK1o5QnVN
            ajN5UjhHZWZ3MUgxMFVSU2JKbjlqMGMKYeuf1xZcq4QpI5oPBCKd3kVPcjwQp+1q
            zXQTtqy4xtyCjIC63629DtnYl6iqUWBozHJp0YRBVRPPevqZPj4D7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ns0hnk5n6sw9uqdn7v4rynumjk0zd8zfsjhegka74xw55nnluy4qtju5um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTlRtSjB0bzZXZVl5REVL
            b0xaY3ZycVhBdy9jNjNXanZIK2tZT3JGd0M4CjlBYjNuL3R3TEtRWGtsek8xd3po
            VXRqZGhsYXdTbGs0dGJWcFJlUkhmTFUKLS0tIFloalVYUjZtd0RON2p5T1VXdmYw
            QXVqdFFpWWhvU29CaDJza0hRU2xUN1EKjAxJDVIYyV3EpeQMDsp5hGuZolXE0J8l
            Wx6WqaL/xi4OsDCwDMBL0aY35Ot702lpRteV9Lp0EMDhh82PNb9v/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10w46rzpkfyx7cfx8hy6dq059cw8zy7mrvtu2gc06hngyxspeh9aq45ssty
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPV2hTR296SXIyMUFNSEx3
            c0trVkllU0hrSzU1U2ppWEhvNjRHMmdQejM4Ckwwa0NPaGNnK0VMNzlHSGd3Qm5O
            cVA5eDJIMmVvY3hFMWprdnNqQmswTjAKLS0tIDNWeTRDdVNxMEFtSnVDU2VxZFR2
            bTZ3ckU0aGExQ2hhVG8weUd5NzNEVkkKEeL6MvcgeFfhlWOyRsybZTkJAze6q7+W
            +F76nrBsqnpn4VWa3iGl+sLVfg2yzJLMU1y6Xtu4H8IKfDYxjCPwQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T19:57:40Z"
    mac: ENC[AES256_GCM,data:MNhTSPgG7GhDH6S4QRsTAebtrJSd27nlkpRAGciTCbHgut0ytoar3p2YxA9Bx5un+YOq1W2zvbYCAdVC1pk3ltIFnPwRD7YtE3tEgZnP1LPZiCL86pDodN+TulY5uhgfIovQo/aWv2JrXGkrJxJ5/mJJjcPdDehPsqlDrD6KO9U=,iv:v2TkfAUQ/2DFE3/UEAFeXKgaIdEDLPpoGQMQsKfi0kM=,tag:38aeYfSBfXxzvCLxbtxPYQ==,type:str]
    pgp:
        - created_at: "2025-10-06T14:19:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz/c2vn977oWAQ/6AlV9jmYdaLRmfJ5ZgF2bpfqa5DrKW2BFRlFqnWMuxgbs
            b4uKZE04v+/2Sob1qOlCM24zIL+0Y80nJQu8lvfhD4yv4OT1dNkzWq3F1ZsP+Wte
            2qqDF3g2KmksDbQ5hv4aZYsu6JlPcQtsF6YqYnf/itPGKm80qHBm4gFxfyxZSm9s
            5F4mCvtI0WDJq/+V08IYFApEygq2ozceVurhVmJj+lTm/OqrGG0YBpPl99AzFps1
            rgvr0tEiF1QZ7AKTtlS5bv8wn3vEE0YDBjNbeUrenhyK1WKsDnMgdvOzINliRVht
            P1x2iHFhXlj0hcvzsj8ZUGKXdqRBWMBYX0CskHObMI08ZFiWx5IwQvMY+rEc/pgR
            hVYS8BTQl2PJUNCVdNudGqmXV6fOyuclr47TE8bE+nFxOQ6LQ5EuxSsizE3jkI6/
            v+E2Xyt5JE33i8dhS4Zf+y5VIDelk2myy4fCAXJl0QedOP2yMuRv+XX2sc729xgS
            Kf/2pC4bed2ehtBPRM01YOO5WLYSMd3VbO4Uc9IqCZZN02hgFKPYUqO0qp/0xbvj
            Svj4kI66w8lUjVlvvDU9ZMN0wvh9sQPBbVmo+SChTAu0P9GCWfACjFUZ2vlgEkqh
            1y9+NXk7JDfdzCG8JEVE2wBs1lV+df5pdjAeFHNrBolYhSJ98OGsdTKdrLurQf/S
            XAFhJrfnOsmOFeWWRHFh933Ce3SBQwZQPkXzLjs8KXKLX9Y3lxt/m+/mqS2HFMbN
            Tm6TQt7xbue/sL8pKAtnkRnz4T0/hsBOyd1cFOdOUjO9dicXOCxLvY7DXdcy
            =3l5B
            -----END PGP MESSAGE-----
          fp: 978C4D08058BA26EB97CB51820782DBCACFAACDA
    unencrypted_suffix: _unencrypted
    version: 3.9.1
