pgbackrestSecrets: ENC[AES256_GCM,data:/id9hvlhZZgSjOUek6xVcMo5N0zOp4rney376omLrP2GZ/jeQnp8Qydkrb4FkVjQWuS93g5QJnRRINqnoHfZLuqe9iLZ0SP2fj4C36L+/QcODcOUbw7Hfl1kdgcihLB0uMLwrSFUHPBgf+7sVzSVgnt2ymopxba4Tsr41k2sPvX1Cgua3vDVhmnhu9jsSQPZURGVDwxORfJKYVVNxWvP40IRnrh7mEiBwnMzsGFtTFRUA5Cu0hLaR71GtsCCARDTEwfE4f6TH0bgN1f0Ppmq6FN00znZOWp2yOE1a8FgcIvxhNedUQ33/W34Pmh6cGzB6OReAdHoD1UAUb0d1OHcPZWD3KxR/2mFWOnwL5Zgjoo5k9D/aJJsvnQxdugDYcilmEHLQtPCjvQxSxdS7Sb/TmZAsZO+c/Qla9/mBKEtMJaqjMt0NObviYw9u/VFhtEWq2vhqkawv/77kqZeKhqEnYTOe8AHQhL1faR4UMcxwEB1f63+6Uwe0eXGIJlrfX5zm+b011jvzaLH5wOy4jzG,iv:zudDBtY6E4cuvDUpkuNinNEjfske4Xd5j+7SzDsjH2Q=,tag:bhkANw0Jw0zx4Mm5fRBPmw==,type:str]
bunnyApiKey: ENC[AES256_GCM,data:vccE0sT5xabMba/lHzpacH+fHUSiealW7kPA4z21jKYjF/8wMU5th/uo8QgtPlVV8skWw2RWERg4UBVC8Fgo2g9d3IqNyA1K,iv:BHzdeZ2Emfx+GgYawOULOYxQ2YDQxBsrDX3hw8MbNls=,tag:SC+nZ0GE0WnJsJPx9a7Yjg==,type:str]
davis:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:olo1T7VLiF5HMm0rvnftXhau8FiucA35QVsAtYU21WA=,iv:nm+OfGI2biCSK8c64K4fYDd6haJN6kBr6pLDShdvHrI=,tag:el7A50JXjZmfzxqiEJwh1A==,type:str]
    APP_SECRET: ENC[AES256_GCM,data:DbMEiVqGVHHNah1tDDkdh8wZJHlPgRukd37TWU+nEQJLUDdI0P/VXz7hUtcYPtgf,iv:sQW8b6rv0+3i44vZgPt8fgP3eHSWpcw0BPdwK0VNtSA=,tag:K/Rc7dpblY2kstffnoc3lA==,type:str]
invoiceninja:
    app_env: ENC[AES256_GCM,data:ZMKIrh6bj4cb8mGsrvs+x8RXwADB9nzax6QdG3fSCCJ/MMEcXyM+zHriqyMBIIPsRCknNCR+XRU3orqvezVbxFFAMxa9tumBQkaVWK0BPl564LfujCwss7ugD+iTDk54/SdAc7kWew/2HeqSnUVVNXfpk1kA22EPXddKHlUWJeUSnsEeAjii//HyqykKwehVz3kw95kC/4MiR5T5GDm9qe82y7clb0hPl7DU4JdRFeD/WRXdfDKtrrVrYnYfBELQFj35FoxZutH7K7O+SoDRXO538Ldu72zdQy479O/H3ag1fDth,iv:bfsnAP0Bt8e87a2fPNTHPeIbok5jzBNQhu9FzCnAy5s=,tag:ndOaRMn83hkpujmyczMcrA==,type:str]
    env: ENC[AES256_GCM,data:CtoDV7HBpQU9wybVB7Gkj6hmI7WlpXI+cDS9eij6GbDc0TwqSsVPWKEefQ/ay7qYYDMsJV4Hsy9ObrNu,iv:y9x6/uEgZEQ7+wTEHywEudsRx3POmRcPyzpw0Ijes4w=,tag:cVbVO2nfOlegwGcgO8Xf6w==,type:str]
authentik:
    env: ENC[AES256_GCM,data:PlmalXslC7HI3sQxeQ08HARc5BqV6RRnkvgkLvFCp+hzmmhJGm5mPeX9OemJrRXUbfR0hq9TgUlMwK4eFmi+2lypVdV7+CnbYdUAlsnwSS795Z/5TqtcPvgjVghpURg1anNGVxFQ5gZklaNRaOBbuaSrlR6QsSGkRMfg9ViV8apmzG6Uh9YPdQiG9TEm1ltMswrjnHp881RKIketRK2aKnBQ23IrVMph1ehJS0CcOqITF3zKApalcajZ7CBBxKBN185HYZQc/xzt3DQ/H0hcmRKp1q6Yqn9PRFj9wIcpsMwPZQC5BI+vXDGFZTQqQpqe556GTnPrXX5jDbtcYHEzwY+D67lVMJ+e9Zk/ZHXZBxDqz3AP5+gkdWrV+EfrzWBmF5TUFPZFeLEGXRssfIJk7c39s+ficDNLhQAoIivpOJNyDP/9FLSi/xqa1LQ3VnsMa9f6N9upo/pzP01ueN7DgyvbUJmug4NJo1fPQ26nU6qTMrLOpMN/bxIKZkNAIFN5z/hPI/87sfChjgSU8/2Gvg==,iv:n2KXZhfUcFcX7e2fee1vkh/9rqwXO+LEeF5KGveqdiY=,tag:tT3F9chkUSBifd26M9kvAw==,type:str]
paperless:
    adminPassword: ENC[AES256_GCM,data:l2LBGcEGJrY7utZlFZwb31+8syU=,iv:ptypm68YwYRcCKmBUXfVlfWTbYY0xGGF66QqZ5z3iFI=,tag:79hilJKk++0WwL7Hfuf92A==,type:str]
gickup-github-token-label: ENC[AES256_GCM,data:p1e5zrakOWF8hsGzyotoB5UrR+Y=,iv:KbiKBljIJNSNHKdyjXHzmHqNpl2SLtKyqxVGI333Lts=,tag:W2bbWKzVLQgq3lEMDQ9jyg==,type:str]
gickup.yaml: ENC[AES256_GCM,data:hiNpgfyYywRBc2MyVBxihzlq2qPGuOX2oZ7vXLuxMTdjO0HbMJXmXo4gq/2J4jBxMNUAXBLv1lcfSLTEJY2SYHKoQOeu+ShYA1/DzFxdvcfI18y+gQC8gZuii7LlPqdAL5ADlulkxc4cmvoXefsNV18WnSdn393Lt7qFXF+Uw1KsRqijhrNHSOp68k3BE8im7zLW5BkOLsuTPlS+l7FmqnGOGFHIhI8bTql5Mf7+uy2YkBL/faSBpBrfwDOAX5sYjLSCdHQPVQv2VveWWxSaIKZnTTmVgVi2nVapwpkUQvhNOKLpebieulgd4jxI+KkfbpHoC15S1KYPhBUFsuj9CxtTxtMlMCDytYoqWTW7lnj/QpHPiNBGz5ET/MvtYPbcFR3UAWJvGSSU3THgbX6Gc9lxsXRt9qbPVmna4FBeWUru5uWZnNzGiUjl06Bfl0zywyhZuN+p7pLHFhEQ0Is04CfmPZC9OwdLT7t/qkR2TkJ1b7XKxTpx1XFozajlArjE84OU4lv7rxzyfe+PrufuKcQ16PLr9Ya2WSbgwAQyNXwreJiO1lGuVMsW1Ypa+OGkF6QDSTqJevnEZSpXP8Gd8pjMcA1JWAhDx/4uxcuoi5nHfI10e6rJj5WK8rQ4FpPXuxkhE3Mq5Mi8,iv:IlgU97zqFlwP3barPmwojWO4XnxV+XarW50L39MhOBc=,tag:OnKYHfe1U85+gaNU1pWiNg==,type:str]
sops:
    age:
        - recipient: age1yubikey1qt0lmjdz8l27zy8gqlwu5hpplunz5dcsszuqjau7q7sdnksjqhm5cg2jkkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDR0TFMwUSBBMG00N0lF
            enExam5VbmlrQTZLQmZoZE03enA1eGRHR1QxeWpjK3RGcVJobApzQXZuYUtJZEZm
            NmZiMndqMTVQeGtOSUdIbC9XSEJOUVNRWitpSzlxVU5BCi0tLSA0K3dySDZpaFdH
            dTQwRnBzdnFmR0gzd3krb3YxRmRRcGtrWHNSQ1lnRFJjCgUhbQ7ws2G2km0cbig7
            64DQGUtHacygfOfN7V8+Ep7s/YKWYN57gb8lOlL6BQyq6uC0IkB4EVQDegv28qST
            rxA=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qvm060q3kense6l22nrjd5a9gqsm9k4eaanhuk5h3hpmvzes8xd6584fsvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDVlcW1kdyBBNWZQdGp6
            R2p1M3JwUVVjV09ZcWZxRXBUL3N0aGNuRzh2d0VwS2J3ZjBHRwpLbENNMlZ0RHkz
            VHZxc0NHVlZjcnpudVVVaU8zeHN5cW9vS1Z1blFCTW9vCi0tLSBMYkpsaG1tYndQ
            U01qNmpaU2JLVklBMDMrd0pkUGt1SXRaZThFOVAvdGx3CimchIzqjxqs4sc+plit
            EYxu9nvRJoTF9PnA5dz2EkJHQJ5gUXUIweDdF4hxyIYzJE1/MWYl+C3Fzp0du3Vi
            FCw=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15j42dspmmwprjau6l48xp05d97s8ml5s3tjxrfwvm37tvuynssuqtsevkj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeGFMZmJPbUVreXNpaE84
            Qm1mVFpxVVhNZGZJeW90ODFURW4wVUZBYkJNCmRNdjJLNTNGM0tBeFcxUHhEVUhx
            M2xVNERDTUhTR010VE1EbVl2MTI5alkKLS0tIHM4NVNHNVRLWXJ0RWltcU9JeHNX
            UVVCdjB0TDNRNm82TW1xdkpnbytRWm8KAu5CS6OBI6CBz5NsIVniJ1w4gRTRzvWr
            3lEoBSak52n8CUArOciMyEbUdsSp8Y2LpHIhueUt0kZnaU8N4PRgrg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dtwmd5txsdjh3agr7zlqum8h024hasarflnpfavyqsu7g2lvvyksv8zff5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTmJveDlzcDJsbDdTRnQw
            bWRwc3RuYjBxbFFiZjlqSUJoTlJxU1JzVGpzCkY5L2FyYk9NdmJLOTBBWGxaTEth
            WVBqdTk0cTh1OCt6d2MxYk9vLzFUUTQKLS0tIEZGNFNyNHlsWVhkOUwvRFBXR3k5
            WjJqV1VXdDRwcjB1dVJKS1YzZ0JQUVEKKXaastu2WTmcD15lnjFNyICYVPt8V6gI
            ebQh9S1NPmzQFwt6tKUXI4C52BGADbur1tlNNOi2AulnEHmjoFAhLg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ns0hnk5n6sw9uqdn7v4rynumjk0zd8zfsjhegka74xw55nnluy4qtju5um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSlB4SUVRSHBkaE9WbklE
            dExDdkFVVlRlNHBqS2paVjFDVG1wZ1hEWkVrCmdvVUI3TGcyUXZ4VmNvMlVPRG9C
            UklGb1oxbkxWdzJveXB4UW80MEY4UXMKLS0tIDJPVW9oQ2prTVZFNXF5TWRqY3dm
            NlJvOHQwb0FHaDYwS0V5djI5YS9DczgKE67azkXt3RU6hGNmuFwMz4zJU7aDJK0t
            +bdgJORaDZZzNS6cauS86ssfD++xmLQQ7IXo+hgk2Isl4SKv0UzpYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10w46rzpkfyx7cfx8hy6dq059cw8zy7mrvtu2gc06hngyxspeh9aq45ssty
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQzNZU01YVlVxM1o0K1N5
            Q1VBZlBIVEJZUW9acEtDQzFLVDRkbTBGcjNVCjhEMTRibjBOVVNBS0h3WTBRYXJ6
            SHlWVExmdG5XcElsOFhUektCcGQzMFUKLS0tIGJ6MnRsS1JUOUxIZG1wY1Q0NkZJ
            aDF6c1p5N1pRVEljeFVlUmpqL1NibHMKHatcmoyeDz5xoXe8NxTOar70JL4v3veW
            zqBamzKfE/u5yMY8Yw7BH05kht4uPZuX2bBrbXJsR2OMctGLMUrC0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-08T14:59:49Z"
    mac: ENC[AES256_GCM,data:pW2C2NnTSxyHg206OT2nwB2+CFN55zO98nX1fFqTD65Ot1i0BFUUv0/GpS7pMt1CqCDjxAI8vNh33F4eTNCK045i2rakvF+6re3NivBPlBowTLjZ50dUQcQTFarTwmp/UREpVmbznZbfUZPkFzbD94d7NyKw01cQ3mTIqR6nb8k=,iv:OU/S0lmXomX8sSkLejDbsqaf9Odi6j9M2s87L0OZV28=,tag:BaECisjNFR3b0X6gbVzRrQ==,type:str]
    pgp:
        - created_at: "2025-10-06T14:18:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz/c2vn977oWARAAq+/anQuXVOEDLC4/3W8q9/POkj842v1VZT8Wl1ZnyGNw
            lkqVNMgOZvhJmilE8RZupfwN8UxgfJyp+IDpDkRRKTf2TsTq3VXZynNfsS3dk/pd
            GwqUu17mhbm8Myl0XHNLlcDj547Ur/Aa6ivi7Lb+GUHOd6+t73rS+yUuTkFnI4Qk
            zpsUw5dXKkO6Hkk/2FoEabd653UvTeQ26yOM2HoAOhYIhUMn363Xlpq0hhIszuGm
            C58jBeNuG+oT17qSnk9SPL9C6oqMGfGp44htpw9PLKwDzKs5KDO9qrN8DNEndmtf
            I6BtNnuXYHUtiJLm430N/YIZwryxjZJ5PCIaOISiTMc4ad+gfGPH4myyGVz8MdWb
            +i1WHyIqwJw8hjQftE2G9EQKsVo2q6XdYBP/ixHEHrjoVpbCUM1TLS3J8uLFsRtt
            TF4bEGwVf83Azzwsgqt8T0s6y2UHyQpT+p9u46c5Fv/WIiZLzIQ4atP5jXUKuozN
            orUVDQlSewE12U2nXPt0I/BSu7S4W39unI56mXa6wSZpqYmvi8mjeybfRiZZLfPc
            d1lz2ac1p8nbfzi9Lq3JPU7CWsqdKYne1DJwK8SRogNVFVFexzDf63sKt00YKiqq
            R0rOC9YEEyVGBurrRcD+nnSBCpGyODm3PwdEkglre5m4LL835eS0eO53RCrpfxPS
            XgHC4pX5BKKgNf9ep2qqvcN4DRsOaNJr7nesQ5AsMwb2LpOFXezy8uFQuA6LoMwF
            +z2uI6PQfKz2nkQ3jWI0peKhNdqFVeaDtALUCkg6IqPIAvN03otdWqBVCulbDbA=
            =4vg6
            -----END PGP MESSAGE-----
          fp: 978C4D08058BA26EB97CB51820782DBCACFAACDA
    unencrypted_suffix: _unencrypted
    version: 3.10.2
