pgbackrestSecrets: ENC[AES256_GCM,data:/id9hvlhZZgSjOUek6xVcMo5N0zOp4rney376omLrP2GZ/jeQnp8Qydkrb4FkVjQWuS93g5QJnRRINqnoHfZLuqe9iLZ0SP2fj4C36L+/QcODcOUbw7Hfl1kdgcihLB0uMLwrSFUHPBgf+7sVzSVgnt2ymopxba4Tsr41k2sPvX1Cgua3vDVhmnhu9jsSQPZURGVDwxORfJKYVVNxWvP40IRnrh7mEiBwnMzsGFtTFRUA5Cu0hLaR71GtsCCARDTEwfE4f6TH0bgN1f0Ppmq6FN00znZOWp2yOE1a8FgcIvxhNedUQ33/W34Pmh6cGzB6OReAdHoD1UAUb0d1OHcPZWD3KxR/2mFWOnwL5Zgjoo5k9D/aJJsvnQxdugDYcilmEHLQtPCjvQxSxdS7Sb/TmZAsZO+c/Qla9/mBKEtMJaqjMt0NObviYw9u/VFhtEWq2vhqkawv/77kqZeKhqEnYTOe8AHQhL1faR4UMcxwEB1f63+6Uwe0eXGIJlrfX5zm+b011jvzaLH5wOy4jzG,iv:zudDBtY6E4cuvDUpkuNinNEjfske4Xd5j+7SzDsjH2Q=,tag:bhkANw0Jw0zx4Mm5fRBPmw==,type:str]
acmeSecrets:
    email: ENC[AES256_GCM,data:GuRw/L7oEWUz/ygoQd+kNkRF+pMNKec=,iv:KvqUMor5pChGoBQCJaYRECAqy0/P35fZgbfYGKWXlOI=,tag:IWERANp8CdpwPWVHjltJ6w==,type:str]
    cloudflareDnsToken: ENC[AES256_GCM,data:imZ2Gl6KxxNyKrGMNzXmDsVGJvyxy9OTjAFmwUceqRBoZEZTpOGI2g==,iv:1flBLmav8ziwcQVCkDC+S7WLYyaL2MXfg73WL95zVBY=,tag:jNJ2zfJaOj1gqrj217RRzg==,type:str]
    tokenName: ENC[AES256_GCM,data:CEcnCDC+7de/oTsZLQfLloVNmsuV,iv:sbKZHujZjXduYcd0pwNt+VeebITV8vpA09vgGHD7VPM=,tag:mvhK2MlUNaA58VAizkru6A==,type:str]
davis:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:olo1T7VLiF5HMm0rvnftXhau8FiucA35QVsAtYU21WA=,iv:nm+OfGI2biCSK8c64K4fYDd6haJN6kBr6pLDShdvHrI=,tag:el7A50JXjZmfzxqiEJwh1A==,type:str]
    APP_SECRET: ENC[AES256_GCM,data:DbMEiVqGVHHNah1tDDkdh8wZJHlPgRukd37TWU+nEQJLUDdI0P/VXz7hUtcYPtgf,iv:sQW8b6rv0+3i44vZgPt8fgP3eHSWpcw0BPdwK0VNtSA=,tag:K/Rc7dpblY2kstffnoc3lA==,type:str]
invoiceninja:
    env: ENC[AES256_GCM,data:CtoDV7HBpQU9wybVB7Gkj6hmI7WlpXI+cDS9eij6GbDc0TwqSsVPWKEefQ/ay7qYYDMsJV4Hsy9ObrNu,iv:y9x6/uEgZEQ7+wTEHywEudsRx3POmRcPyzpw0Ijes4w=,tag:cVbVO2nfOlegwGcgO8Xf6w==,type:str]
authentik:
    env: ENC[AES256_GCM,data:PlmalXslC7HI3sQxeQ08HARc5BqV6RRnkvgkLvFCp+hzmmhJGm5mPeX9OemJrRXUbfR0hq9TgUlMwK4eFmi+2lypVdV7+CnbYdUAlsnwSS795Z/5TqtcPvgjVghpURg1anNGVxFQ5gZklaNRaOBbuaSrlR6QsSGkRMfg9ViV8apmzG6Uh9YPdQiG9TEm1ltMswrjnHp881RKIketRK2aKnBQ23IrVMph1ehJS0CcOqITF3zKApalcajZ7CBBxKBN185HYZQc/xzt3DQ/H0hcmRKp1q6Yqn9PRFj9wIcpsMwPZQC5BI+vXDGFZTQqQpqe556GTnPrXX5jDbtcYHEzwY+D67lVMJ+e9Zk/ZHXZBxDqz3AP5+gkdWrV+EfrzWBmF5TUFPZFeLEGXRssfIJk7c39s+ficDNLhQAoIivpOJNyDP/9FLSi/xqa1LQ3VnsMa9f6N9upo/pzP01ueN7DgyvbUJmug4NJo1fPQ26nU6qTMrLOpMN/bxIKZkNAIFN5z/hPI/87sfChjgSU8/2Gvg==,iv:n2KXZhfUcFcX7e2fee1vkh/9rqwXO+LEeF5KGveqdiY=,tag:tT3F9chkUSBifd26M9kvAw==,type:str]
paperless:
    adminPassword: ENC[AES256_GCM,data:l2LBGcEGJrY7utZlFZwb31+8syU=,iv:ptypm68YwYRcCKmBUXfVlfWTbYY0xGGF66QqZ5z3iFI=,tag:79hilJKk++0WwL7Hfuf92A==,type:str]
gickup-github-token-label: ENC[AES256_GCM,data:p1e5zrakOWF8hsGzyotoB5UrR+Y=,iv:KbiKBljIJNSNHKdyjXHzmHqNpl2SLtKyqxVGI333Lts=,tag:W2bbWKzVLQgq3lEMDQ9jyg==,type:str]
gickup.yaml: ENC[AES256_GCM,data:hiNpgfyYywRBc2MyVBxihzlq2qPGuOX2oZ7vXLuxMTdjO0HbMJXmXo4gq/2J4jBxMNUAXBLv1lcfSLTEJY2SYHKoQOeu+ShYA1/DzFxdvcfI18y+gQC8gZuii7LlPqdAL5ADlulkxc4cmvoXefsNV18WnSdn393Lt7qFXF+Uw1KsRqijhrNHSOp68k3BE8im7zLW5BkOLsuTPlS+l7FmqnGOGFHIhI8bTql5Mf7+uy2YkBL/faSBpBrfwDOAX5sYjLSCdHQPVQv2VveWWxSaIKZnTTmVgVi2nVapwpkUQvhNOKLpebieulgd4jxI+KkfbpHoC15S1KYPhBUFsuj9CxtTxtMlMCDytYoqWTW7lnj/QpHPiNBGz5ET/MvtYPbcFR3UAWJvGSSU3THgbX6Gc9lxsXRt9qbPVmna4FBeWUru5uWZnNzGiUjl06Bfl0zywyhZuN+p7pLHFhEQ0Is04CfmPZC9OwdLT7t/qkR2TkJ1b7XKxTpx1XFozajlArjE84OU4lv7rxzyfe+PrufuKcQ16PLr9Ya2WSbgwAQyNXwreJiO1lGuVMsW1Ypa+OGkF6QDSTqJevnEZSpXP8Gd8pjMcA1JWAhDx/4uxcuoi5nHfI10e6rJj5WK8rQ4FpPXuxkhE3Mq5Mi8,iv:IlgU97zqFlwP3barPmwojWO4XnxV+XarW50L39MhOBc=,tag:OnKYHfe1U85+gaNU1pWiNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gxvdmyxmx4rczdaqaah8ysrwwpcladf9llax5ppleutesrwnxp9qxd4l69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTjI0V2NpSlpoQmd5ZDRF
            Z1dEaGFiU3NOUm5WTjEvM0lvTUdvaytpTjFnCkdjSjdJSkZEakIzK0grTGVlR1U0
            Ynp2YVpCMDZWNGlKSkxIZlU0eUMwQ1EKLS0tIDE3ZG1OeEtiSnZLUGFXS05VY1FC
            QWJsVklqay9hdVM2UW1ibFZ3WCtUd3cKDS8JxRO8AAPpeC8YQNAx6JnBWFNM7w9Y
            9Fdsuz8gpKo0yFSJk2dioGNudRZpZl8ujLafjG0kfM/OzC6VH+BLaw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rd4msy9hc7t7703kwypmt20r8qwkuqxyxuk3sd95sw2sc9gvjydqe67dn2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWnF4ZHI0dk5tOHBicCs1
            L203UzNGdW1uc0g5cXRoYjRXU3RuMnB0WVZRCktxUWd6U3dtM1lWQ3hmZzVDcWFI
            WnZBbEloWDdGR281aDQ1MmQ5YzJEREUKLS0tIGd4Q2RoMm1ZYld6VHBkKzA2NWdD
            KysvUW5xWWp0NDVSOUp3RDFBSjZwM2cKoAvxAeQKSY5Da3VNNqJcoI2mZ/C/g/0R
            8BtJC4ZFKu2QmqQn7mzbweKnJMiLT3Uf2kp6AvhTJ3ziOr7YDrc/Fw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18aeezktqhdqyh90zathz7uea2tqhgh52l2m6v6xjy06s008d69cq4glx7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRGZpcC9sbWJobjJWU29Y
            anRjVUFWSnJCdW8wbitpYVJycFRtZUJ6Y3dzCnQ3VEtkOEZqWDdKS01YalM2UXNm
            Y3NlSGZnK0R1QXFDL1o5R2pkVjFMWm8KLS0tIE16eGNEYmI4WDR2WUErSXNHampi
            RE93VGl6YXpDK0RGR2tBc2RvOFhVRDAK5c2mxX2CU8Dahm0xVnGwN2m18nwSTl5c
            qPqpb9ek9nWgiEkZEV7tt4RfJrLKs6JeXJ0/n9w+xIfq/lceE5spJQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dtwmd5txsdjh3agr7zlqum8h024hasarflnpfavyqsu7g2lvvyksv8zff5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwenc4bDdLRnlyekM1SThX
            b1NpRnJHWmhLWnFieWNsWis0S21NRU03MWwwCmdFdjE1dW1sVENkN3NNU2NPVDZy
            NjlJSHlGaUxqUmJhNXQ4S3RuOWFrZTAKLS0tIDlsZDdyR094VFc1Rk4xSldBUEZD
            Q2grKytTTUJjNkkzRGlXcXZ3RzNlVDQK8FwKKdeebYkama2QMvflS550ivKUmFrI
            cAdgM9FtvvMt+pBns6YD0qqe+Z79htTbULJ9CUuUFnjX1jBW3Xo+LQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ns0hnk5n6sw9uqdn7v4rynumjk0zd8zfsjhegka74xw55nnluy4qtju5um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ay9yNTB6YU0wamowbko1
            WEpGazk2ZGYzN3E3QnBweGRQai9ibVRFUFJBCnZJSEVxT0ZhdDlrRzBINTZJSnlK
            RU9wZTQ5OW92SU83ZGdlKzVCc1J3elUKLS0tIGV4ZnQzZlZiM0RlbjA0VlBQZ3NE
            K0g5djRGQjBtZUZDdTVNZzVHdG1SV3MKuimjfDXte72TwkD/B/wu9Qpor408HdOs
            2M2ztILkdOKhvS8yLKKVM7KFptB/5UCf1UX1XFBTWVePfAM94+RXag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15j42dspmmwprjau6l48xp05d97s8ml5s3tjxrfwvm37tvuynssuqtsevkj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbG95TkU2N3Z5UUIwbDIz
            UjNyWXlqTTlrZmR0VnFndHBpMVR0TExUQUdRCkFFcEVVTEk1NWt5eUJyL3hCTEFN
            RlJsWXVyeDRiQjZPSG5CUUJmVFRUMG8KLS0tIFBSdmJSK2pZdTZ6ZVc2VG9nNUtG
            VUR5MzJNZnFsc0w5Yyt6TUF4ZjFha2MKsamWU4y8kfBP0l+Zgr5PoWZcnVZ/0flX
            bj0iQ5DolwtL25UyG7K0ruFt5c4wvGS/KyJ06z4ohxjO8AfjOeOpUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-11T11:15:04Z"
    mac: ENC[AES256_GCM,data:8/Gh5H2HMl7V8n2qc+lXEDfgEhmsMDCWwsn5W2EUSg8qbTxhH0M/T83P/E+bLqLgLHXMOaA76QBAoPNCG4rD7x840ye0ojxvYuS7cvFixiWIy2/gIVRTsvRqOmMbAyI5I8nH2/5I+PxwjoYD5H5/sCL1KWzioSFA3hFh9Uu+eYE=,iv:rmlfA1CI7oCGfsRLLNaRJl9RrV7AB/q7ki4+3RQ3MVg=,tag:ET3AqXVpjOXgUdH9FmVxMw==,type:str]
    pgp:
        - created_at: "2024-04-08T13:09:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz/c2vn977oWARAA10yYYMBXLPfKtpJu0vcNm58D/P+2Xtv/QxubgyAYoshd
            Yx05tA2zlbEycKOOYlrVs3fKK/zfXAfaIlZcZecf5PMlnqcWzAi1BqeZ7TBiVrIn
            vLwuGyAPBy62IHo51lQM4WVX3e1vuePI41z5bwLCYiT2w84HjYwtn7Z2nWYbW61Z
            KY5+o6P6pMH92nFJaMyq4Reqau9dMIT8C1LsF3qGnKsGu09Jw/x0JWEq0C0ceZEe
            Ieaz5eDPKLFZ1O3Cno36m7miXxT21X4IbR46NgPK7VQA9tJJoqvL3HmOahX9KJY9
            tdsUOGjQC1xyd40zbvfnfXsG8qD6wxgNf+rngGIXSBFefpmHs9PhV80HQRxr0J8A
            eoEMtrSNL3Fen7E934SBZDEB8t05eOCeONj4aLZvQ6LF3tQqlDJO3xaSiLe8hNOt
            18cIbppkrPslsMHi3q9qj7IsBVHaEcgFXH3uL45SvXmMEsPbbGbIkbcd2nNPp20A
            mr57HuOMX0AdEsCDhidQP1tJqrETDPf9/SlrK1M4rnuOVFEk/4uqrVGn9LmPytmA
            DE+DaIFWJXG/4TDKRe5+Llk+NntSzIbVReF8nCB4ulp71traTgqgw41fytnRp1Lc
            CE14gyP+Y/d+l/vjyDDd6ntJbUfSr8R7d7IW0VjPC7U+bj3eenxUSFm/97TD63PU
            ZgEJAhCO7KwvWvyyLdaV6NKQ4yeCNkvkPhXuSLqRKLzCuc6S3IALaFyZBu3qZ6aT
            Qsx4ihX0I19e9S7HyyO+0UgWv0JaY3jhXNz3KqieHqz1iBqjOp0C2Mm1kgdcE1Co
            K1xFQS37Wg==
            =hq6q
            -----END PGP MESSAGE-----
          fp: 978C4D08058BA26EB97CB51820782DBCACFAACDA
    unencrypted_suffix: _unencrypted
    version: 3.9.4
