pgbackrestSecrets: ENC[AES256_GCM,data:/id9hvlhZZgSjOUek6xVcMo5N0zOp4rney376omLrP2GZ/jeQnp8Qydkrb4FkVjQWuS93g5QJnRRINqnoHfZLuqe9iLZ0SP2fj4C36L+/QcODcOUbw7Hfl1kdgcihLB0uMLwrSFUHPBgf+7sVzSVgnt2ymopxba4Tsr41k2sPvX1Cgua3vDVhmnhu9jsSQPZURGVDwxORfJKYVVNxWvP40IRnrh7mEiBwnMzsGFtTFRUA5Cu0hLaR71GtsCCARDTEwfE4f6TH0bgN1f0Ppmq6FN00znZOWp2yOE1a8FgcIvxhNedUQ33/W34Pmh6cGzB6OReAdHoD1UAUb0d1OHcPZWD3KxR/2mFWOnwL5Zgjoo5k9D/aJJsvnQxdugDYcilmEHLQtPCjvQxSxdS7Sb/TmZAsZO+c/Qla9/mBKEtMJaqjMt0NObviYw9u/VFhtEWq2vhqkawv/77kqZeKhqEnYTOe8AHQhL1faR4UMcxwEB1f63+6Uwe0eXGIJlrfX5zm+b011jvzaLH5wOy4jzG,iv:zudDBtY6E4cuvDUpkuNinNEjfske4Xd5j+7SzDsjH2Q=,tag:bhkANw0Jw0zx4Mm5fRBPmw==,type:str]
bunnyApiKey: ENC[AES256_GCM,data:vccE0sT5xabMba/lHzpacH+fHUSiealW7kPA4z21jKYjF/8wMU5th/uo8QgtPlVV8skWw2RWERg4UBVC8Fgo2g9d3IqNyA1K,iv:BHzdeZ2Emfx+GgYawOULOYxQ2YDQxBsrDX3hw8MbNls=,tag:SC+nZ0GE0WnJsJPx9a7Yjg==,type:str]
davis:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:olo1T7VLiF5HMm0rvnftXhau8FiucA35QVsAtYU21WA=,iv:nm+OfGI2biCSK8c64K4fYDd6haJN6kBr6pLDShdvHrI=,tag:el7A50JXjZmfzxqiEJwh1A==,type:str]
    APP_SECRET: ENC[AES256_GCM,data:DbMEiVqGVHHNah1tDDkdh8wZJHlPgRukd37TWU+nEQJLUDdI0P/VXz7hUtcYPtgf,iv:sQW8b6rv0+3i44vZgPt8fgP3eHSWpcw0BPdwK0VNtSA=,tag:K/Rc7dpblY2kstffnoc3lA==,type:str]
invoiceninja:
    app_env: ENC[AES256_GCM,data:ZMKIrh6bj4cb8mGsrvs+x8RXwADB9nzax6QdG3fSCCJ/MMEcXyM+zHriqyMBIIPsRCknNCR+XRU3orqvezVbxFFAMxa9tumBQkaVWK0BPl564LfujCwss7ugD+iTDk54/SdAc7kWew/2HeqSnUVVNXfpk1kA22EPXddKHlUWJeUSnsEeAjii//HyqykKwehVz3kw95kC/4MiR5T5GDm9qe82y7clb0hPl7DU4JdRFeD/WRXdfDKtrrVrYnYfBELQFj35FoxZutH7K7O+SoDRXO538Ldu72zdQy479O/H3ag1fDth,iv:bfsnAP0Bt8e87a2fPNTHPeIbok5jzBNQhu9FzCnAy5s=,tag:ndOaRMn83hkpujmyczMcrA==,type:str]
    env: ENC[AES256_GCM,data:CtoDV7HBpQU9wybVB7Gkj6hmI7WlpXI+cDS9eij6GbDc0TwqSsVPWKEefQ/ay7qYYDMsJV4Hsy9ObrNu,iv:y9x6/uEgZEQ7+wTEHywEudsRx3POmRcPyzpw0Ijes4w=,tag:cVbVO2nfOlegwGcgO8Xf6w==,type:str]
authentik:
    env: ENC[AES256_GCM,data:PlmalXslC7HI3sQxeQ08HARc5BqV6RRnkvgkLvFCp+hzmmhJGm5mPeX9OemJrRXUbfR0hq9TgUlMwK4eFmi+2lypVdV7+CnbYdUAlsnwSS795Z/5TqtcPvgjVghpURg1anNGVxFQ5gZklaNRaOBbuaSrlR6QsSGkRMfg9ViV8apmzG6Uh9YPdQiG9TEm1ltMswrjnHp881RKIketRK2aKnBQ23IrVMph1ehJS0CcOqITF3zKApalcajZ7CBBxKBN185HYZQc/xzt3DQ/H0hcmRKp1q6Yqn9PRFj9wIcpsMwPZQC5BI+vXDGFZTQqQpqe556GTnPrXX5jDbtcYHEzwY+D67lVMJ+e9Zk/ZHXZBxDqz3AP5+gkdWrV+EfrzWBmF5TUFPZFeLEGXRssfIJk7c39s+ficDNLhQAoIivpOJNyDP/9FLSi/xqa1LQ3VnsMa9f6N9upo/pzP01ueN7DgyvbUJmug4NJo1fPQ26nU6qTMrLOpMN/bxIKZkNAIFN5z/hPI/87sfChjgSU8/2Gvg==,iv:n2KXZhfUcFcX7e2fee1vkh/9rqwXO+LEeF5KGveqdiY=,tag:tT3F9chkUSBifd26M9kvAw==,type:str]
paperless:
    adminPassword: ENC[AES256_GCM,data:l2LBGcEGJrY7utZlFZwb31+8syU=,iv:ptypm68YwYRcCKmBUXfVlfWTbYY0xGGF66QqZ5z3iFI=,tag:79hilJKk++0WwL7Hfuf92A==,type:str]
gickup-github-token-label: ENC[AES256_GCM,data:p1e5zrakOWF8hsGzyotoB5UrR+Y=,iv:KbiKBljIJNSNHKdyjXHzmHqNpl2SLtKyqxVGI333Lts=,tag:W2bbWKzVLQgq3lEMDQ9jyg==,type:str]
gickup.yaml: ENC[AES256_GCM,data:hiNpgfyYywRBc2MyVBxihzlq2qPGuOX2oZ7vXLuxMTdjO0HbMJXmXo4gq/2J4jBxMNUAXBLv1lcfSLTEJY2SYHKoQOeu+ShYA1/DzFxdvcfI18y+gQC8gZuii7LlPqdAL5ADlulkxc4cmvoXefsNV18WnSdn393Lt7qFXF+Uw1KsRqijhrNHSOp68k3BE8im7zLW5BkOLsuTPlS+l7FmqnGOGFHIhI8bTql5Mf7+uy2YkBL/faSBpBrfwDOAX5sYjLSCdHQPVQv2VveWWxSaIKZnTTmVgVi2nVapwpkUQvhNOKLpebieulgd4jxI+KkfbpHoC15S1KYPhBUFsuj9CxtTxtMlMCDytYoqWTW7lnj/QpHPiNBGz5ET/MvtYPbcFR3UAWJvGSSU3THgbX6Gc9lxsXRt9qbPVmna4FBeWUru5uWZnNzGiUjl06Bfl0zywyhZuN+p7pLHFhEQ0Is04CfmPZC9OwdLT7t/qkR2TkJ1b7XKxTpx1XFozajlArjE84OU4lv7rxzyfe+PrufuKcQ16PLr9Ya2WSbgwAQyNXwreJiO1lGuVMsW1Ypa+OGkF6QDSTqJevnEZSpXP8Gd8pjMcA1JWAhDx/4uxcuoi5nHfI10e6rJj5WK8rQ4FpPXuxkhE3Mq5Mi8,iv:IlgU97zqFlwP3barPmwojWO4XnxV+XarW50L39MhOBc=,tag:OnKYHfe1U85+gaNU1pWiNg==,type:str]
sops:
    age:
        - recipient: age1dtwmd5txsdjh3agr7zlqum8h024hasarflnpfavyqsu7g2lvvyksv8zff5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVVVCb2tJV1RjeG05Q3c2
            ZVNURjJVcVcrdVRaekY0NHlWVFhNZE5ZN2lnCkIyeHlXU0RUZ1dSblFDNFQ1UHBE
            UC84a0tBNFJaZk8xMWlhOGphZ1pSY1EKLS0tIE01KzkwNGYrdzlaUXFya1NJWVQw
            WVluNDNIUW1Rd0xFYnBtTFlzUnJFYlkKhLv3xzdPXpinshqMt9uT3EqzGNbSjPNv
            J8Wcys51hynKHTG1G/oZG+AtUS0Ef7bqVaRQMpfVgEG4BHka6g3y/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ns0hnk5n6sw9uqdn7v4rynumjk0zd8zfsjhegka74xw55nnluy4qtju5um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWlhyVkg0N1BRNDdIRkdS
            YkpoWDJmMExPVjdWOGNUbWREU2h4amR0WTJRCnVqNjBwK0d1NVdRZm5OS0REZFZv
            bU5nWXpWaVVDaUxFS0xHM3NuTUZTazgKLS0tIDZZeFBDcll5dEFkWk9WVjI2YkhL
            NlF6TjVxNm1EdDdvVkFqT01FVVhzMTgKml1sjozV4GWk4i0f4EDPipMV5Sa4NOZ7
            xD92Ughe7zv2NhOCawBhEYq4LIt2Fq02h/48dGDHY0/rr1nw20KfQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10w46rzpkfyx7cfx8hy6dq059cw8zy7mrvtu2gc06hngyxspeh9aq45ssty
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcDdUQmoxZDBSbjc5bXVv
            R1B4ZjBEbFdwOVF1c0pPMlhFcEZodUxXSkFVCkdEOUo5UW9EOXpaN21nMGJkbWxR
            enZvTWZHdC9UaDdPdWZXTURLMFZpWlkKLS0tIGFMM2MyRzgycjZQNUFkc1lRdmds
            Ull3NVp0UzMzVXMxRjJ3eEw4dnN2Sk0KvdtdO1EFXPekayDTXTyimM0vm/jsgg9q
            EbmSHy96F0d51fSL/47xTF5soxdMnfb7N84eZkW5N4VJZkCbCsgEPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15j42dspmmwprjau6l48xp05d97s8ml5s3tjxrfwvm37tvuynssuqtsevkj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MGd6Qjd3WTN3ejhJY1JW
            cytFYzFCRW84ZmFzdVlVaWMzdkVkcVBSYlRjCkVtUGpnd1U0M0lUYVRwazB3OWNo
            WFMvZ2dxdlNuK0crcDlQM1ZtbDdzblkKLS0tIGpFU2pXVUhUcE5LOGQvOC8zZlY5
            R29DZlJsN0Q0Q0pUWlhzWU1HMFBQbWcKzoOpE8bmQwc+13M8dsPiT2Vvx7npKrtd
            JhMpi8LY9mYIW98SJ+rp59SA2YjGzm9uEgO2cY+cN92FqezRVafPww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dzr2v5py0vwj3wujdmfgcfjqc26vz07u7vl0j8la345y97f0au2smk79jd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WVNNWnJOc1c2S2RxdjVr
            a2ZSN2pWejlROEpjaS9MQzFaYTg5WkRTOFVzCkpKVXZSM1BtcEd2V0VwSi82cEVV
            QWg4MUxhK0xQTk9ERlJRTzJJbWljQlEKLS0tIGRkM0Ztb1duU2FaTjZKTUlkaVcx
            SnRrUjI5TFFPRlNqOTNBKzNtQ2U4REEKaRcafWvT8fPsdOlhr3mcJjRx/ba2oVA0
            bmrGfvbMVE5I95wBqAEhKQM7/CyFydT3kmUqnahQO429drmim0ZDLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-08T14:59:49Z"
    mac: ENC[AES256_GCM,data:pW2C2NnTSxyHg206OT2nwB2+CFN55zO98nX1fFqTD65Ot1i0BFUUv0/GpS7pMt1CqCDjxAI8vNh33F4eTNCK045i2rakvF+6re3NivBPlBowTLjZ50dUQcQTFarTwmp/UREpVmbznZbfUZPkFzbD94d7NyKw01cQ3mTIqR6nb8k=,iv:OU/S0lmXomX8sSkLejDbsqaf9Odi6j9M2s87L0OZV28=,tag:BaECisjNFR3b0X6gbVzRrQ==,type:str]
    pgp:
        - created_at: "2025-08-23T20:39:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz/c2vn977oWAQ//aT5YvFmQ9G9dvLc+iRrW9/gw/vHhRkNVnbr1eGgDtaNT
            tsFRgRQUC5AwD6NaqzWrJALSXVDjUqErkdlqLg5BkMYn/MgfH55Pq9CWiFdTdB6b
            nvE6MF05CIcSfIezAaa/Hl9i9oOAcyYyi1uOCb5Wb0YtWYfAGkeEtco43hqdy753
            EkVXNmf1hr74UOvbOBEGUeEpVSfL+t/V1NlFlgGyNJImN1rlxPJwIP0rZHty5Rra
            ONlQFlEE/ICK6LY6I9I76WrZ0rEHYAe9c7yVp2ovDo6gimBI6y0mUJ799laRbRQ8
            95AZXzqz2vdiMGPpCBJhvsU17eUzGwXcDn0f7WJCJ0D+ZL1OcR5XMmU9VxEj0PQF
            0J11qaRGZQvpHnPjrD+IkcUA9LiXawiS65qK2pE9xJkM9Tw1QZDhNldswu043VrC
            bSywZZWHQn+PQ+wWH5RkWWLZVI2netK9Y5ZnlsrNRv0XrhuiaYpP4Dd+XtO9H/di
            2YdToJleMvANeyHcNBZobgKxufkQRqOc5B7y5VSX5v+dRkCzTZ2Dd8DjcRBKO/LK
            vEHrugIyX0FSy+5dMiWWSMKnRoIIP6bJX9nXCW17kWdKsBShL+NzERDnD1tLom1A
            5iLgO/BWFYUGIGC3z1uSIVxbh/+HX+ZmHNP+f2MqpfkY0ZyY9LYCvKOnvGzqIMbS
            XAFQMieAjMI3gcNE6o08yWCRJiaNV40uNl+0quq0OInkUK43mHoX0DK9sQpUd2uV
            hVg79j7Yh3fnb2HXs5kuXEPGRO1BHAmGJWanvHRoLyo6VnRHQNTXyMJNVnHe
            =YMXZ
            -----END PGP MESSAGE-----
          fp: 978C4D08058BA26EB97CB51820782DBCACFAACDA
    unencrypted_suffix: _unencrypted
    version: 3.10.2
