pgbackrestSecrets: ENC[AES256_GCM,data:/id9hvlhZZgSjOUek6xVcMo5N0zOp4rney376omLrP2GZ/jeQnp8Qydkrb4FkVjQWuS93g5QJnRRINqnoHfZLuqe9iLZ0SP2fj4C36L+/QcODcOUbw7Hfl1kdgcihLB0uMLwrSFUHPBgf+7sVzSVgnt2ymopxba4Tsr41k2sPvX1Cgua3vDVhmnhu9jsSQPZURGVDwxORfJKYVVNxWvP40IRnrh7mEiBwnMzsGFtTFRUA5Cu0hLaR71GtsCCARDTEwfE4f6TH0bgN1f0Ppmq6FN00znZOWp2yOE1a8FgcIvxhNedUQ33/W34Pmh6cGzB6OReAdHoD1UAUb0d1OHcPZWD3KxR/2mFWOnwL5Zgjoo5k9D/aJJsvnQxdugDYcilmEHLQtPCjvQxSxdS7Sb/TmZAsZO+c/Qla9/mBKEtMJaqjMt0NObviYw9u/VFhtEWq2vhqkawv/77kqZeKhqEnYTOe8AHQhL1faR4UMcxwEB1f63+6Uwe0eXGIJlrfX5zm+b011jvzaLH5wOy4jzG,iv:zudDBtY6E4cuvDUpkuNinNEjfske4Xd5j+7SzDsjH2Q=,tag:bhkANw0Jw0zx4Mm5fRBPmw==,type:str]
bunnyApiKey: ENC[AES256_GCM,data:vccE0sT5xabMba/lHzpacH+fHUSiealW7kPA4z21jKYjF/8wMU5th/uo8QgtPlVV8skWw2RWERg4UBVC8Fgo2g9d3IqNyA1K,iv:BHzdeZ2Emfx+GgYawOULOYxQ2YDQxBsrDX3hw8MbNls=,tag:SC+nZ0GE0WnJsJPx9a7Yjg==,type:str]
davis:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:olo1T7VLiF5HMm0rvnftXhau8FiucA35QVsAtYU21WA=,iv:nm+OfGI2biCSK8c64K4fYDd6haJN6kBr6pLDShdvHrI=,tag:el7A50JXjZmfzxqiEJwh1A==,type:str]
    APP_SECRET: ENC[AES256_GCM,data:DbMEiVqGVHHNah1tDDkdh8wZJHlPgRukd37TWU+nEQJLUDdI0P/VXz7hUtcYPtgf,iv:sQW8b6rv0+3i44vZgPt8fgP3eHSWpcw0BPdwK0VNtSA=,tag:K/Rc7dpblY2kstffnoc3lA==,type:str]
invoiceninja:
    env: ENC[AES256_GCM,data:CtoDV7HBpQU9wybVB7Gkj6hmI7WlpXI+cDS9eij6GbDc0TwqSsVPWKEefQ/ay7qYYDMsJV4Hsy9ObrNu,iv:y9x6/uEgZEQ7+wTEHywEudsRx3POmRcPyzpw0Ijes4w=,tag:cVbVO2nfOlegwGcgO8Xf6w==,type:str]
authentik:
    env: ENC[AES256_GCM,data:PlmalXslC7HI3sQxeQ08HARc5BqV6RRnkvgkLvFCp+hzmmhJGm5mPeX9OemJrRXUbfR0hq9TgUlMwK4eFmi+2lypVdV7+CnbYdUAlsnwSS795Z/5TqtcPvgjVghpURg1anNGVxFQ5gZklaNRaOBbuaSrlR6QsSGkRMfg9ViV8apmzG6Uh9YPdQiG9TEm1ltMswrjnHp881RKIketRK2aKnBQ23IrVMph1ehJS0CcOqITF3zKApalcajZ7CBBxKBN185HYZQc/xzt3DQ/H0hcmRKp1q6Yqn9PRFj9wIcpsMwPZQC5BI+vXDGFZTQqQpqe556GTnPrXX5jDbtcYHEzwY+D67lVMJ+e9Zk/ZHXZBxDqz3AP5+gkdWrV+EfrzWBmF5TUFPZFeLEGXRssfIJk7c39s+ficDNLhQAoIivpOJNyDP/9FLSi/xqa1LQ3VnsMa9f6N9upo/pzP01ueN7DgyvbUJmug4NJo1fPQ26nU6qTMrLOpMN/bxIKZkNAIFN5z/hPI/87sfChjgSU8/2Gvg==,iv:n2KXZhfUcFcX7e2fee1vkh/9rqwXO+LEeF5KGveqdiY=,tag:tT3F9chkUSBifd26M9kvAw==,type:str]
paperless:
    adminPassword: ENC[AES256_GCM,data:l2LBGcEGJrY7utZlFZwb31+8syU=,iv:ptypm68YwYRcCKmBUXfVlfWTbYY0xGGF66QqZ5z3iFI=,tag:79hilJKk++0WwL7Hfuf92A==,type:str]
gickup-github-token-label: ENC[AES256_GCM,data:p1e5zrakOWF8hsGzyotoB5UrR+Y=,iv:KbiKBljIJNSNHKdyjXHzmHqNpl2SLtKyqxVGI333Lts=,tag:W2bbWKzVLQgq3lEMDQ9jyg==,type:str]
gickup.yaml: ENC[AES256_GCM,data:hiNpgfyYywRBc2MyVBxihzlq2qPGuOX2oZ7vXLuxMTdjO0HbMJXmXo4gq/2J4jBxMNUAXBLv1lcfSLTEJY2SYHKoQOeu+ShYA1/DzFxdvcfI18y+gQC8gZuii7LlPqdAL5ADlulkxc4cmvoXefsNV18WnSdn393Lt7qFXF+Uw1KsRqijhrNHSOp68k3BE8im7zLW5BkOLsuTPlS+l7FmqnGOGFHIhI8bTql5Mf7+uy2YkBL/faSBpBrfwDOAX5sYjLSCdHQPVQv2VveWWxSaIKZnTTmVgVi2nVapwpkUQvhNOKLpebieulgd4jxI+KkfbpHoC15S1KYPhBUFsuj9CxtTxtMlMCDytYoqWTW7lnj/QpHPiNBGz5ET/MvtYPbcFR3UAWJvGSSU3THgbX6Gc9lxsXRt9qbPVmna4FBeWUru5uWZnNzGiUjl06Bfl0zywyhZuN+p7pLHFhEQ0Is04CfmPZC9OwdLT7t/qkR2TkJ1b7XKxTpx1XFozajlArjE84OU4lv7rxzyfe+PrufuKcQ16PLr9Ya2WSbgwAQyNXwreJiO1lGuVMsW1Ypa+OGkF6QDSTqJevnEZSpXP8Gd8pjMcA1JWAhDx/4uxcuoi5nHfI10e6rJj5WK8rQ4FpPXuxkhE3Mq5Mi8,iv:IlgU97zqFlwP3barPmwojWO4XnxV+XarW50L39MhOBc=,tag:OnKYHfe1U85+gaNU1pWiNg==,type:str]
sops:
    age:
        - recipient: age1dtwmd5txsdjh3agr7zlqum8h024hasarflnpfavyqsu7g2lvvyksv8zff5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxK1NCMWp0bGtXaXVDdnN4
            VXhoVjJhWUpuWFlCQTRGNFR6K0syZFRKZFJVCi84RVJ1V3VzNmI1K0FKanJzMU5S
            NkNZZVM3RFA5ZXNBWHlHSjhLRHVkdkUKLS0tIExBb0dPM3Y4ZGdpZ0tUWTc1cnVR
            VTBZUWt2cEFUa3FJL1JWUWdkSnhtZWMK0mpSZE32sl980swzTuFeLWRMMVWkaX9z
            f8mrjAWZdDQa3GI6r6xk5SPuQdK2ut4w5itFJcZsUIHDidjU9v3ezQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ns0hnk5n6sw9uqdn7v4rynumjk0zd8zfsjhegka74xw55nnluy4qtju5um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdkdJSXFNTllVc3JzanlR
            ZUdUWVBEc0hDN1MzT1hBMjRlR0NjT3pHMkJzCmJuNG1aekU4NU9uemZuTEYwdlZ5
            anZUSGYwSVZGZUV6Tk1nZ1dVbEwvSzgKLS0tIHJMRlFYTVgwVUl4OW85cDN0MGNI
            NWhyaEkrMVJjOGJvZzVMNEZ1V2MvZDAKuqttkxupBnKIBAWQQ2dnruKywyrD7ykM
            b4Z7GC5b6wLeVwLKdabm71LCBx2F2muPpL/UGW37zSi6fsuA5HyGbg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10w46rzpkfyx7cfx8hy6dq059cw8zy7mrvtu2gc06hngyxspeh9aq45ssty
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTG1RQ0QwTGJNNnhOMmpn
            QzRtL3A0a0JqbXRxVk5YUmVhdDNIUjhCY1NNClA2a3Z5UlJPT0J4L1hzaFlESTBQ
            ZHdmTGtkd0JRSFJmVmhHdmdkSkc0T3cKLS0tIDlTN0hIeEtsR3lCZ29EdmdHOTJU
            TkZncXhuaEdFU2VaVnBmM1YrSGU0Vm8KuoMaQ5V6vlhRoCNhWI3q4fQoc+jedPlz
            ub2GdeI9NLo0vErb+CQ0/pJVPNIjFqQVWnYH8hYZ5fF5o4c5qs4bUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15j42dspmmwprjau6l48xp05d97s8ml5s3tjxrfwvm37tvuynssuqtsevkj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKc0Y0N1hjK1hsYW5hREJR
            VGVYOFZyek9JcWZxUysyQVNaNmxXZ0JVcndvCkdoNDYyT0F2MXdUcWRqcTMrdzZr
            V2hyNWllNmxxTjNFUmtCZUpRT1Y1d2sKLS0tIG02N29jdUhVc1Bzb3YyeXBoSTk0
            YW5MZ1BTR1Ewak9aWHVTWFNidGRPZGcKSb/KdDCl7RmUa6MeU9FRqLtqy5nr9hFY
            qjlVaFoVdhXanB9IpyTva7I+88OVZXXI5ODZDAuCL0rPkRTFU7Ygnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-04T12:40:03Z"
    mac: ENC[AES256_GCM,data:0N5FqVMWqAk7bwtvQwF+a0WFBZt7Kg44MInbPrNkoH8ar9kdrGpfDpDbVDzcbPZTkwMft9U86Qc0lwsdR5EcCmE5niefAC/vPnBJtizt/sQ0VbXrC5E6IAJrDIfvwFA90Ks3HqeUFTfJUCO+2NPDE/Rl12AhOvydzdBNYffYZ9A=,iv:CQCF3mG4tJIOAErD0hL9tNP+A1JsUjYhV+aEDM1y3lo=,tag:kEJ5ofGgo81wEPSjM5WPOQ==,type:str]
    pgp:
        - created_at: "2025-06-04T12:38:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz/c2vn977oWAQ//UAxkuqD6kq0iYcJALyCs3mGo0XS5vO8eCb/9pA63FK/O
            ta80WTnnx06ldCRfQaxk8K6aLvB4/yF1NtmhtNJn+aX18DYVNK/V5L+jAB3FkZ7w
            e+dpdbJ82cRzFf9YqF9iamlV0/mZIvV6+3Z5wJKIEMAvo7W1y6dk7mkemi/DU0Wo
            FtlLKXdFaEAil1v66QvFbiilBvHoNONJo4PN6PXTxfoUl+7rYWkqPrQxSsoEmUOS
            s5oheid83ODtUjqDqKrRKPK92K1JxF4ns1iMWvPdKQQ4g6IcE8vZ3sG/SROtiBEh
            3ymFeyvKfy/WaJAJ2S467+aoCde0L3qn9+cDOaSeN9LZxaZqUWJsw1k8yYOH0t5A
            7Bk/9jNBbws9PN0tX3YsCyq6FHMZan0mC6THDRMy6V0o6ykAuRIoXq2CHYTfvdU8
            HZQygASV82cf6wIIQ4Yz9XuzJkcOpRZZDtQJuozOLbHilDIAi78G45/ARRiG+CYx
            hCaaLLtdd6aIJQSxbbIltRSNLTZGomMtduanNL5LAWE5yDwRnXHqlfwXzWWkT3TU
            7K+HZObhvFQ2L7MhoWYQMpSsoXZ7r+IVDUGpIwukJbaho03lzbCLQUjE5Nku3N8w
            nxbrGvcEvFduBXYmySK4RY+gYICzs8KXI7hSNmtQeeyRI9W+oeciPq2d+yrhifnS
            XAEYo4MkBgLIUkw/knekmqgcm6KUoniRryubi3BaflpTo4IERQI8E3K9NQpekk0l
            wyJOl0TWb4B9Pdr/7dbunONgQDQxD0nd6cUdCi4dN7EmUviupES8oL4olTqu
            =mtye
            -----END PGP MESSAGE-----
          fp: 978C4D08058BA26EB97CB51820782DBCACFAACDA
    unencrypted_suffix: _unencrypted
    version: 3.10.2
