home-dl:
    gluetun-protonvpn.env: ENC[AES256_GCM,data:TQ1V2zel9bKjdh87xkD8cri1vN7b+OGmY40vJw0f05HQ4uxS+KabrWGKp86IW0WZis/zENG5Tz3FDJrsYmB5DCOKNnu+JnX+Yr7FsKNa3EpAq36BoJEPnVajrSABRZ8n,iv:uOcmIV2N10dB4jvIHvQQv4W/1Q3UEdFXsGnZDYdURFM=,tag:DfG9o3dJB/ldunbgQFl4KA==,type:str]
proton_config_dewey: ENC[AES256_GCM,data:/InajpBZLHlUIPa+fEBLa385IVsn8A3pBgOzSHoi5jyyS0+DkDSo9iAl+HTXI5PdYigKpVxB3x26wHwuQJmRWTaIX/N2bk/YWv2+mMJT65r/aYQN8XG5aXRfcfZMtB0PehginXfy7jXw0Om02ZI6qrxwNLfdUEfeS70/67v4h7ho/79OUZ5LMPGvuUnRVfXW9BJDE5pLkcFE3U3V0R5Gm2tI3ZBayRK2i9qJAzNJD3rD//21GrCG6jd6MSCkqdQ0FVDTV6bYKT5s3YCYiBwUKL0+hX8zGd5uszOCcPxvZDSaNskp/7uiMZm39qJIRApj+TaZ8nB8axIi3Q3eFcLLl8TE0DKCf01zQGN3+jm4NdeDDMa3aQjV8GcjH7aouzCR2CfylCp2EyOb5rc/3oQ9fVsE9KZ1Hoo730X1JWbh/u29ahgxDHIVLVZ2QWlYu1DMkg49zav7lsG+dswRbun+IL4kINm1G0sZ91ovAJeaCURz4eurNnynyJVRpQMMzps1ew18hv3/ZSu4qMA=,iv:5Iw36rEZagS/Z6UTFFDP0SsuBOj8swJN6LvM9oI0gJQ=,tag:NW9poJw8cZsSWyq2Z0YD+g==,type:str]
pgbackrestSecrets: ENC[AES256_GCM,data:/id9hvlhZZgSjOUek6xVcMo5N0zOp4rney376omLrP2GZ/jeQnp8Qydkrb4FkVjQWuS93g5QJnRRINqnoHfZLuqe9iLZ0SP2fj4C36L+/QcODcOUbw7Hfl1kdgcihLB0uMLwrSFUHPBgf+7sVzSVgnt2ymopxba4Tsr41k2sPvX1Cgua3vDVhmnhu9jsSQPZURGVDwxORfJKYVVNxWvP40IRnrh7mEiBwnMzsGFtTFRUA5Cu0hLaR71GtsCCARDTEwfE4f6TH0bgN1f0Ppmq6FN00znZOWp2yOE1a8FgcIvxhNedUQ33/W34Pmh6cGzB6OReAdHoD1UAUb0d1OHcPZWD3KxR/2mFWOnwL5Zgjoo5k9D/aJJsvnQxdugDYcilmEHLQtPCjvQxSxdS7Sb/TmZAsZO+c/Qla9/mBKEtMJaqjMt0NObviYw9u/VFhtEWq2vhqkawv/77kqZeKhqEnYTOe8AHQhL1faR4UMcxwEB1f63+6Uwe0eXGIJlrfX5zm+b011jvzaLH5wOy4jzG,iv:zudDBtY6E4cuvDUpkuNinNEjfske4Xd5j+7SzDsjH2Q=,tag:bhkANw0Jw0zx4Mm5fRBPmw==,type:str]
bunnyApiKey: ENC[AES256_GCM,data:vccE0sT5xabMba/lHzpacH+fHUSiealW7kPA4z21jKYjF/8wMU5th/uo8QgtPlVV8skWw2RWERg4UBVC8Fgo2g9d3IqNyA1K,iv:BHzdeZ2Emfx+GgYawOULOYxQ2YDQxBsrDX3hw8MbNls=,tag:SC+nZ0GE0WnJsJPx9a7Yjg==,type:str]
davis:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:olo1T7VLiF5HMm0rvnftXhau8FiucA35QVsAtYU21WA=,iv:nm+OfGI2biCSK8c64K4fYDd6haJN6kBr6pLDShdvHrI=,tag:el7A50JXjZmfzxqiEJwh1A==,type:str]
    APP_SECRET: ENC[AES256_GCM,data:DbMEiVqGVHHNah1tDDkdh8wZJHlPgRukd37TWU+nEQJLUDdI0P/VXz7hUtcYPtgf,iv:sQW8b6rv0+3i44vZgPt8fgP3eHSWpcw0BPdwK0VNtSA=,tag:K/Rc7dpblY2kstffnoc3lA==,type:str]
invoiceninja:
    app_env: ENC[AES256_GCM,data:ZMKIrh6bj4cb8mGsrvs+x8RXwADB9nzax6QdG3fSCCJ/MMEcXyM+zHriqyMBIIPsRCknNCR+XRU3orqvezVbxFFAMxa9tumBQkaVWK0BPl564LfujCwss7ugD+iTDk54/SdAc7kWew/2HeqSnUVVNXfpk1kA22EPXddKHlUWJeUSnsEeAjii//HyqykKwehVz3kw95kC/4MiR5T5GDm9qe82y7clb0hPl7DU4JdRFeD/WRXdfDKtrrVrYnYfBELQFj35FoxZutH7K7O+SoDRXO538Ldu72zdQy479O/H3ag1fDth,iv:bfsnAP0Bt8e87a2fPNTHPeIbok5jzBNQhu9FzCnAy5s=,tag:ndOaRMn83hkpujmyczMcrA==,type:str]
    env: ENC[AES256_GCM,data:CtoDV7HBpQU9wybVB7Gkj6hmI7WlpXI+cDS9eij6GbDc0TwqSsVPWKEefQ/ay7qYYDMsJV4Hsy9ObrNu,iv:y9x6/uEgZEQ7+wTEHywEudsRx3POmRcPyzpw0Ijes4w=,tag:cVbVO2nfOlegwGcgO8Xf6w==,type:str]
authentik:
    env: ENC[AES256_GCM,data:PlmalXslC7HI3sQxeQ08HARc5BqV6RRnkvgkLvFCp+hzmmhJGm5mPeX9OemJrRXUbfR0hq9TgUlMwK4eFmi+2lypVdV7+CnbYdUAlsnwSS795Z/5TqtcPvgjVghpURg1anNGVxFQ5gZklaNRaOBbuaSrlR6QsSGkRMfg9ViV8apmzG6Uh9YPdQiG9TEm1ltMswrjnHp881RKIketRK2aKnBQ23IrVMph1ehJS0CcOqITF3zKApalcajZ7CBBxKBN185HYZQc/xzt3DQ/H0hcmRKp1q6Yqn9PRFj9wIcpsMwPZQC5BI+vXDGFZTQqQpqe556GTnPrXX5jDbtcYHEzwY+D67lVMJ+e9Zk/ZHXZBxDqz3AP5+gkdWrV+EfrzWBmF5TUFPZFeLEGXRssfIJk7c39s+ficDNLhQAoIivpOJNyDP/9FLSi/xqa1LQ3VnsMa9f6N9upo/pzP01ueN7DgyvbUJmug4NJo1fPQ26nU6qTMrLOpMN/bxIKZkNAIFN5z/hPI/87sfChjgSU8/2Gvg==,iv:n2KXZhfUcFcX7e2fee1vkh/9rqwXO+LEeF5KGveqdiY=,tag:tT3F9chkUSBifd26M9kvAw==,type:str]
paperless:
    adminPassword: ENC[AES256_GCM,data:l2LBGcEGJrY7utZlFZwb31+8syU=,iv:ptypm68YwYRcCKmBUXfVlfWTbYY0xGGF66QqZ5z3iFI=,tag:79hilJKk++0WwL7Hfuf92A==,type:str]
gickup-github-token-label: ENC[AES256_GCM,data:p1e5zrakOWF8hsGzyotoB5UrR+Y=,iv:KbiKBljIJNSNHKdyjXHzmHqNpl2SLtKyqxVGI333Lts=,tag:W2bbWKzVLQgq3lEMDQ9jyg==,type:str]
gickup.yaml: ENC[AES256_GCM,data:hiNpgfyYywRBc2MyVBxihzlq2qPGuOX2oZ7vXLuxMTdjO0HbMJXmXo4gq/2J4jBxMNUAXBLv1lcfSLTEJY2SYHKoQOeu+ShYA1/DzFxdvcfI18y+gQC8gZuii7LlPqdAL5ADlulkxc4cmvoXefsNV18WnSdn393Lt7qFXF+Uw1KsRqijhrNHSOp68k3BE8im7zLW5BkOLsuTPlS+l7FmqnGOGFHIhI8bTql5Mf7+uy2YkBL/faSBpBrfwDOAX5sYjLSCdHQPVQv2VveWWxSaIKZnTTmVgVi2nVapwpkUQvhNOKLpebieulgd4jxI+KkfbpHoC15S1KYPhBUFsuj9CxtTxtMlMCDytYoqWTW7lnj/QpHPiNBGz5ET/MvtYPbcFR3UAWJvGSSU3THgbX6Gc9lxsXRt9qbPVmna4FBeWUru5uWZnNzGiUjl06Bfl0zywyhZuN+p7pLHFhEQ0Is04CfmPZC9OwdLT7t/qkR2TkJ1b7XKxTpx1XFozajlArjE84OU4lv7rxzyfe+PrufuKcQ16PLr9Ya2WSbgwAQyNXwreJiO1lGuVMsW1Ypa+OGkF6QDSTqJevnEZSpXP8Gd8pjMcA1JWAhDx/4uxcuoi5nHfI10e6rJj5WK8rQ4FpPXuxkhE3Mq5Mi8,iv:IlgU97zqFlwP3barPmwojWO4XnxV+XarW50L39MhOBc=,tag:OnKYHfe1U85+gaNU1pWiNg==,type:str]
sops:
    age:
        - recipient: age1yubikey1qt0lmjdz8l27zy8gqlwu5hpplunz5dcsszuqjau7q7sdnksjqhm5cg2jkkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDR0TFMwUSBBNzNqZlpS
            VGlXdm5aUng5M0l4K3JSenEvTGthZTczdXkyQkljL0N0RExSTQpkdFIzNGtmMGxQ
            S3RNazcxa09tRzdhc0tucWk3R2tvcE5qVEdEMHFoOCtZCi0tLSAzU1A1NVR5bWhD
            TlZPZVRxLy9mOXdBR010VS9GUjRXcTJBR0lXRXVZRDFNCtnBh8ATe4dWqcqX8YEO
            iJfUwc3mtRWo/zhZMnJfMNZCJ4zAj12dErXUG7F/wkT+8AL6/khU/ondr58OaJRl
            zRY=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qvm060q3kense6l22nrjd5a9gqsm9k4eaanhuk5h3hpmvzes8xd6584fsvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDVlcW1kdyBBMzhvdXpC
            V1pzajY3S2RjTmE3RG1UTUZsc1lVYmRiVGhISGxzSHN2SmFKbgpZdUs4ZlVSSUs0
            MDRiMlBXZFVCVnpIUVhHTkxLbzkybERNUG5HNUo3cjZRCi0tLSBxNi94VXhpZnU0
            T3RSSFprMVZlQW9zZkhGZTYzYUFuRENZcCsyNnVWMnpzClzbbE0Rt6lLpoh94gs4
            b3oI5H1To/QSbjLERDYvl1Hu65kdf4LFnJuM+02vlLaZQqOmcsl7BmIpVQINxBIc
            /Z0=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pq1txa5jfq4y6xn2w6aj778jkyu8wsm47ke0pt05jm4dgmhj7chenqcnr0rq47y2sm4kacyp49w9wcyyc7z29luwrlvjcd0y7n7urnjkvheqx3nyl0xpvvwhdw0vkahpd5e9c8ctn7ej68y93z56eq4tw0cg92425tsmrr4t3frkwkyrv2t59ldwnsscwhqwqxtyv6q6gvrfj2trrclscvjd4plcsrtj8vhq9cc0f0sujwd5vuum59rnaxc4se0sh9uq223ln9n0hyt29m3578he24urp625k6wnmgkgmsncnamccy48wleaxzqrsnc463rstpgc7s3n3mu35457aasshr8n43s290f2s92kqps2n969h8g0djexymceqlqvq5ctrp68a9m5k0x5chxhqr7a7tr55n4r3wcynnwdyyehpxxp2ap25yt6hxqxkphtveyagd8wsa0dkah4mluj7nhd2ddlxne689h9euk6smsj8yfhda8kr8lw72vgjckwhzeeqxspxftgpuyr79q52ajdh0kz6duf2xlx4tr35z9ntfj3arzq4jehz0yjwrqwecsk4469x8p94ekswhfhp8mxagceaehgytvntn7nz6zeg832rp5vznmxndv5avc2ttlhgxuqvpssk4x3gl2xw80ksgz0gzru4d8gz3jlue82wtgk2pvhswle42ldecnrnx5klmhf0nsgywhkanzajpsg8dkgvf5yxgfjqeu5xn06vnmvepvfdkr5jand3ja3uz9axut35jvp85xjkrzlxtz5wvl29zqfkc8yxwujykx6v23njd33cufge9h0nt5400glvrfndd4hjfvvywh8rlq39lwl9f5yuc66n4v2ufzq0sgzrnmtz92dstfv93f59ymt5a33ds8kxst5997teu5hj8tqwuzk73z5wepcgsqys9ql7sjn5p9z9l2xft8s5zryrz6sstvxuj34p9jm36vsy5sj3z3ec7q8sg4chkeddy43qkqcaf5ave58xq40zngh9y55vjz7du4dtfcddxatwtm3p6pzxpepftqd8pkjmmughhxhdq7e6pealyv9gj6w5ps2tqx24kk7l9kl3zjlemvkvk38qgfva4wfpnjemjfjdjyzmc2sn88e3afz6553gstpffm0uu7d3gfwwm72fd7ezx9sxhffdrrnvymuknugepms79m6pyhjyp7ye366jrp59da07ufgcc6kyfdx26mgnqq74cdzqdr824vzx0vdff0gm8mnpudgmfxnz4r5yue5pln54m0pw542858frvhr30v5xt77cqh0qa29anyt7xuhchx40pf6d7mcz44nerpn5qq4g35qc7ad9kyma5uwrqenythpa7txkns5e5lu8yhuumnlu88yv8zssm5npku5af08tasfmy8kpm483jyddzkeve7asqsxw6x00ra3wg7rqhzu5zr8pykcf03c8cu3w48t2sd72wzffsky93pkwfw3jnmuc78me6t7hfg08ruxnp5xwz56q4f7evl6zuukgnxfrpqyk4aqaq0f7rdhlrfphume8tftsgn8ynjt7rgsgfgas5spn3s4nzrgp7ajurfj678h0d60p3l48e62eeps7q5n6m6n5mxw7mdr9a3sckkah9lctv33zfzvt48v4m4wjxqpywvgcdqs4cx9fedzm8klzkvussp5emv9zv4g3v68tgvfp57ap335kf8sq58h93e3tghudem0vzerqts5pxfel59k5gftsr4cxempk98uumjjdyc8pcwljflyftc6ne6a8lr4gumvtk77yyj9espzlskx5dz8prn38wn5xqfwy3xhjzx8xps5tdckxhaejy9mfjavjhrj68wwwzx809zgkckn63dsg2jqg85h3hnwnpw9rm8jy5udzd62ej52ycwkv7ejwsm6dr4zcavgsua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDRSWTcxTzNo
            bmw4Mjg3V1JGV3pyR0M4UCtLMjVVQ29oYmZTUlRzQURIYVZxT3MvOHp1WDVVS3BQ
            YlhrSktndnZZUGQ0VkdQckoyQmpESVhON3JqZHU0Z1BoTk5LRUhrbFI5NkRvT3ox
            SjcwWVJZRGJJTllIUkM2cnFteGdHNTFlOXBVOHpSTTBtU1lCdy9Nc2V1VzJiSHp1
            QmdvaXJnT1A2L1ROdllRTnUwbXRvZjRLeVJ5ZXpjTUxuL1VMSlVqWDAvc2Vzcno4
            VkRoZUl1UjdtYTJrMXM0ZU0rcnl2WjJ0SkpPSCtyV1d3VE9qRkJXc0FOelRCSjJD
            bXMvejROd0hHZks0ZXRlaXdIZWFQeVlEY1IzMCszVXRvZVlxNzhBUHErRlQ1b0Uw
            MHpDTTdiL0hPNWVOeDlTRW1kcnhxcnUrQU1jR0JOOExPVDluSVNSczBWZjcrTEpo
            Zlh4Nm8zOU1ubDlaem5kaUxKZCtlNHQxalcvUEQ0Nk5taWpLbndUaDFaUytNYVpz
            QmVxbkhScTByejlGNStDUG5MdVZ5bWt5WkhXeU9vUkNFTEhUcm5rSVNmRnczNlZV
            YmVYVWxZUnVEd3JrV2tobWVXdVdGRHpPVlZDUkhSNHZiZEg4dHJJcEhNYzl5Mk8r
            REd6YUtTYWFud3BMWHhZeE1TUm5BNVZGVnV6UkJNV1lQalB2cTJDZktNN21mbmhP
            ZmZnOWV4UlVob21HZFFSeDZBWnNqMU1WdC9KMXZTRjhTM2k3MTIvUERsSUFOdlZS
            QWxlUjMzc1J1U3M4aVJ3OVI1Y0Evb1d3MFlpcC9VV1JJb1h2YkVDWTFwS3ZWTFRY
            UDRGRWdZYW9ma3R4UVJXSXBsMkdobXorR0RIM0o2N25HbjdETjd6ODBwTjJzbGNE
            ckRwT0hjWlBnN0xUUGh2WTk3elNzYjBENE14MzhtYzJ6dWJrZWlsa2EyMDZJSHBQ
            OGt5cTBkSFVMa3RQUUZxQXFpUGEvK2loaUFKellaVmV3d2ZaYytaeVNIdmxweWZn
            Tk5QTkt4NlV1dUhBbEZrTFYrUG8zcnFWQmVFL1BJVlU3bEZGWnlnNnI3bXU4aU1u
            WitRaWtQZldqMTlMdWFKYlJCZmlnVWZMVEJhOEtnc3I2cHBzWkJ3cUxyNzVEUjha
            SHQyYnVGUUwzZ08xUW1WZFRHc0FraGh1SWFtb0Fqb3lSUnVRclJGazBFSXdJaVFz
            NVpzZ1N0UjJDU0MvZkhXTHpiYjdseEthVGtITUtwR3QzRzI3NkpEaFMwaG5CcDZo
            WU9JTVo1OFR4d1NiSnpYZTR2eWhVcXhmZ0tzU1hKNzdqa3lNazYyd1NUTmxtQlZD
            amNScW0wbHYrKzRvWkRVcmpKWVdCbEUyeDBtZVMvdmRPV2p2VWsxVTFOcEhCTWE0
            djdRM25tOG5udlBGV0tHdEE4d2pxSFNkeE5idXZCaW5FbDNqMnR0NnliV2FTVm1X
            d0Q1bmNPdXB0RERmTUFMMS9TbkNxT2p2blVlcmlIRi9COFl5elhMdXJoL21DV01C
            ZkFSMS9UQld4OEhldFA3K3ltTkdqZDNUcGk1R0Z6TFk2Wk9qRlZCQ3Jnb2tFcGQy
            WlBZMy9zNUtjR2Y0VkZlNllWT2xMMHEvb2k5dXUzTlFKZ3ptVVUvUWUxdnBIeFNi
            cmNOdXYzOXVnNWd6VzhHbDRkTWdrbUw3ZDd1dCtwaTVrcE5iZEVKZGNwdWNTT09x
            aEhCdElGT1BQQ3pIbmRjNmM0ZlpZWkRVWjkyNmhKTTFwMzJFRlBUZEx4Tm5kMW1G
            TWtaa2dKRzNEVzlSVWZQRXJYVEpzOXpOb1FQMU1YQWVNWEpoa1Fpb1hwdlFDNTBU
            ZnhlQmtLTWNxNTFidG45NTFVc2Fxb1IvL05aRkVPMmdGa1VjRk11My82eUtWcEh0
            RS9HRit2MzdRSm5TUVdObGhBYjA0bHRuMGdoKzUvc0xwU29IZThoVUpMc2pBQQpz
            TGprSU15bGVOdVlkbUh6UnQ1dGFQL2tReDRQaUw5c21YSzliWmRQbTBvCi0tLSA0
            UDE0L1VkWWR5cFM3MVYzSlR0QzRIdWJqQzRFcWxNQWdoeUtSRzQ1cFFBCknyIL2L
            7rl8IWlM8PnIInjcrR9XUz8Vl80yml8gx6u94MHLZeO9MWOZ0clWp/72v0EK+q9h
            i6AA+cSxoS7gJ0A=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dtwmd5txsdjh3agr7zlqum8h024hasarflnpfavyqsu7g2lvvyksv8zff5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UzBhYXFTOGVtVG1wVmxV
            Z0JpT0E4L3NQYU5nck5YeUQyMzF4b3Nlc1ZNClBtWmZsR2o4SXZyUGVvbGVrQUNY
            UUZzTzFEV1M3Uy9ka0R0NVJPcGlMS0EKLS0tICtJcnYwOGV2bC9QeEhORjkvei80
            WEtMa3dLbEQvM2hCZzhMMVFpR1JaQ2MKYRWCzPz2mNMfE6fiZsHYzp6dS6NJyn02
            QK/4N3DNcP36/JXlL7mAm/E2a6aAHqBQwJcypV0/kln9kGOCVdNTZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ns0hnk5n6sw9uqdn7v4rynumjk0zd8zfsjhegka74xw55nnluy4qtju5um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dlV3bk5KL3ZUbnc0ZUVw
            TE9PRUkyZWNxaWFzVXVOR3hvYnhKTFVMZG5FCmhiVzdRRkJXZTVHbmxxd09vR0hP
            OXFYSlhMWVFtWDdYb3gyTGxad20vMDQKLS0tIEV6S09YMisrTkFNenZ2eCtlckZH
            eUdGQmJwWTZtMktyVGQ5Sjcvcy9oSXcKLZ91S9YAnLCtStV6aBvni0FrfelNHKs4
            6bZZ9SmXD3m3ICcCIQOVuK+v2f3TemYA5PCimsBBsPXEd9Hj1TDnew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10w46rzpkfyx7cfx8hy6dq059cw8zy7mrvtu2gc06hngyxspeh9aq45ssty
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKY3pFZGFXTU9KV1c5dHcr
            T1pmY0h1dko5d2hFc2htdmttNTVQOHpUTnhNCjZQNW9VWGxka21BTExuRTZERGRl
            OG4ycmJ4dDVkNzhDL1VkM0orajBGMW8KLS0tIEZFQXBaMG0xcENJT216UUdKN1pK
            THdZTjB3eU9SUlJQaUZFTUk3S0RpZ28KwgNDblVix3Qeb2p1clIeTBB7ZZO7iuv8
            vvw3AOcsEZleUlU4td8MQgbIEG8p94WbMAoAG/DPIOprK2+1ItVwMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T11:23:12Z"
    mac: ENC[AES256_GCM,data:bpYwLJuxNMHbn/F7SYWvDJHhT32BWP68k6L4rJfQby4w7GX+qjljQiQZlpjFU9JBBdm0q6i6AFs04sz6daDK7whrGwvqhPqEMYGm0Z0EMBT5pUC8A26FUIuaicrhZs53wMTf/lOykqnOaKoUSBaVvFuit7EkYZ511ROrux1Pomg=,iv:vnKPI1AaWnNXNk0GnVHmqQWJ34VCxWO1TM/V1l6v9tc=,tag:KnqwDo8dFZGLzZ1FvrGW9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
