onepassword-connect:
    credentials: ENC[AES256_GCM,data:IsOaBzpicXbHrmhrvj88wSq+LwXfx1NoRXpQrtp8rWa/akRQAIYCYalyTUmJuE+W5axPwQwGGjJRKu7fMBL51J30Dyk/I1ZcJvdL7/1m7SP7hcODF5MOZjaIzmLqEhEeOEyy2W41fAOUvDR3xzAiu/C5TqVBcMBT3DHbLy5v1esSXh8v3gM5b0rJj82kndf9wM8OllYkNIpuTq4iIi6grC5b6zE60b/yQMg7ZOSx4NGJ7vCzQCtlr9YOTpmh9R5rd4F6r19giKZXGLLvaHk/eURG0xr68qFphAJlLZ/x3Ggp644gDdTnzPfgugTht6+6PyZAETMKQ/pELnn2Mshx6ewxF6aZgulcJRW3s6nD6xhVMT+XYrM0lO0JrFk7esboCLr+riFP+VV1LwYutgdbmc5QK9maMyzSwZ7zH+Q79gETnTzZn3H/LUK3CrQvAuhj5PCIrtT5k6zHwXnrnBobnN9B5dImRknLUntH5dVBR9Jfu3WKyPdXsjURnJIR4TAzHwmjnuy4BLoiRDePFokKPp/f1Sf1v/kLxUXZKaMKlJo6ppI4NtOb8aDoqUTNW/i1fqAGJgRf6Tr51yB4hBwwHFVLgC+xoHlZT3LhWNuE0lmFbETGPz2U1m9fsxMzbr5Gva7cx14Udbjr7PFu8MOcHbYiGwcAUOteOqFi0FJnF2y2OYvAORE833N1KsbvHs7XeaqKa6jBvXYEgmXv1vA2NaonU03Gb+YhUQXutt4S7Yddx/ObTzm4/QULx6qmyC5x6MbMYnYoJKnfHtfeIIasBbMeqOCOkXgsGp49rxw+gSwbl+Trwn+lY9UxgEimhc3BMn6txckoqB7ERZ3McHnWiPbOjHt3k1iJYAH6zHgKQsn11XYHYWDLloOysAaU29CBcjSCC4PwLdgv8kcaGgxrNMfbAyVCpsT1bxx9EfjtqJYxBFuXqqMnJh1C+fy84GgLyVEV7FQIklpHfdyOAyDrn6oIYtD0GjDF0NYkmI+uow5GRki01HdvwuZSZHwYNwiuDOSDNKShG4aqQzB/ZSObLTmxadMsXrwhYu5z36Eq0CDcau7Skm+RGsx7RR9GpVoEuYVyexsCdIyvyd3d+8KpRkRcCHBR//ayyKAZsFgeV5PkplRCcxGQc5A7d89mUjeL5v4UTW+q+NWfUsSfjMEDqK1yQzaP6Dj24/W5ztGeIOCZnUHqG3DparqzYFjqLUwx0Re8AUJhv4gK5w3gx647mOOeVYbS4adocBHtlDp+cDF7PXH2mTSluRVWzCHeDsbm2yQYghmx6kZnZHXB5vXO8vSMAYG47WlBfMGk8BjbMQu+ymUAmP0cLXFrBMtd0s8juQBxhm6A5bIIxeFP1SkLhhbkEiqy7ASfaCtblg09M+7WlD5JfSUQZiQJ6NRiGi6dsQ+HI0Yb2ueXrPtM2TJyRQqXDBp5kijBcVTIhwJfz4U=,iv:uZvnYwUCXT+1plHT4iRBu1ckWYnw4us7Bbf3ts7SC/w=,tag:LqEySTSlbiJ7PBBDW0fQhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDR0TFMwUSBBa1pjWWtW
            bVpXR0pNY3ZhRWgzSkNEaHpGb0FTSkJoYTQ4MWJuSWUrRW5ZSwpBdmJVU2dQY1BF
            UlBrV2RQb1BHanlMa05YNS9ObmpoKzJRSldtQ0Q4aGZZCi0tLSBGZUYzdkZ6dlpI
            cU0xNzdjeTFJd0lFb0gwT1BzTHZTanJRSGladkVpcGRRCvme+VrxtHNAKihPNTcB
            T0sIH5TQ43WNTCcWMTz22k+zoEzWmih7pkirR8cswnFrVkSvkUW1ULOHUBRzHzZD
            r2g=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qt0lmjdz8l27zy8gqlwu5hpplunz5dcsszuqjau7q7sdnksjqhm5cg2jkkl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDVlcW1kdyBBZ1FuVW1j
            Qi9XUXlWMGEzTElJVDJnN3BMOFA5cG55SnRIdE9Qd2NWdkIwTwpmM1FLNnNuV3dP
            TG5sTmhielZWZkgwWTd6djA0ejhRTlk4Z2VnYjVPODgwCi0tLSAzTjBPWm9QeDVR
            Q1ZETW5kQ25WMVQyVmkxaUVydFBzaURPQ3ptYWRhUlZFCqq69FEpIwekD2jKBMlV
            zwmGg1l16vRGiEaXvFGRPz4UhYWsSgfpdb34+DDPefTUiTlBRRo2/4t5Hm4pB7je
            UAc=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvm060q3kense6l22nrjd5a9gqsm9k4eaanhuk5h3hpmvzes8xd6584fsvn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGNYVnJuckdL
            c3FVRVR1OTJzQ2FKQU83UTFNbk9jRGRjWGlBS25kRDRXaUJmSXhxQjh0ZE5LMExG
            U3NYVHloZzVmS3NWRlBvY1VLOGZoS211cVZYTUd1NmxaNkwyY243L09uOWF1U2Mv
            NU9teWlXMS90SjdGa2Y2NWFNcnc3ZlJIRUpiSXlKN1hJZlVud2Y0cVh1TEY4MTlT
            MG1Mb2FRZHVMMmcwdFhMNWxRUGdVa0JHNWg4VWFTOC9oYkJWblV4cUlNRDFsYVRP
            cGg3NzFXSEdRUEVuMFZQVG5kR1BPSEtHNFVMT0NUcDVsb252dnVqRkhlQ2lPdDNK
            Z1ltU3pLRnlqSDlmWWlhRzBVUHJHc0FFWTNveHlQUEZjSGFTQ3dtR1pmRXJpRTQ3
            d1lOaElVVnc4ei9mMzkxSjVFMDNVdndKUjJtaUs0azNjeDFTUHZweWc0UGlRc0pR
            ZFY1VlRwbzU0WVRzU2xTTDZERTM4OEt6SlcrZnBTNWZNNGtWNmxZYkZKZmx0OExQ
            THNsUmYwZ1JQelRvMnNCY05QRnJqelMrSGdiSkQ2bmtXMDJDQXUzMCtqWU8rRXFa
            YlYzMU8wZ0RlQVkxNndkYzJiblBJVEppUGZlb01ObEF3allqZEw3ZktSZGFteDcx
            OXp1WmRPZTBYK0JXTklIUmVvWVVzR3VoOXBvYllnVVErVHo0Nm55aGw2OXRTbkhx
            VVhCMjhDNkRjVjNyMUlvZlpacnVMTE1BZjVyVzZGMVFQWndReVNub3dkM1Q2TmZR
            dS9EdE1iWklvT3d3YXpEbCsxTGVGL1BsaEo5UWhON3FLeE1IaDFkTFhTMU5YNlp6
            RGNUZHBtNFBrZXQ3eU44RWU0QUZnUnJRTjhLUGNaZUdiU25mUlpqQWlRWVhFenl1
            UzJrZi92dGJ5OEk4bFpPbEJGdnpyaGVNdUg1bnU4Y2dCZFVLNUhOZDFmSk5reEV2
            Rk5lZDRCc2NiUGxvUllwTE1hMHprYWFva0JTNXJsZDFiMkUwckFTSlBHb3g4TXNN
            TVZQN3JreXA0bDdhQ1JaUk5qT3BSS01ScnFrTXRUQi9CMzVueHBsQlAreC85Wk1W
            TEd0RmJicXd2dWNCT3dYd0RPbUYyNjFvbmFJajZad0VKL01DQk5IcHdXVWtJa1hQ
            QkJ5Wm1CbG8xOXQzQXhUY3JmbjhuMkRyTWVxeWMvNVF3eWJseEdVd1ZNcUR1U1Jz
            S3VWbGlEQzQ2dzkwTXRRYnVJdXdFdmRaSUViWkc0WUFiS3p6SlkxU0ppbU1SUWdy
            NHJkT3JtbEo1MUluVDUyaWJQVmdUZ25qem1GaU9KYi95WEEzMXFTVFVYbDFnakx2
            SGdLZGFqQVJNYUhNeTY4c2ZZK1h4NHQ5NzhyUElKL1RHZ0ZIT2lwUHQzSktoVmFF
            SG4wMCtwL0Nvd2hpby95NzVmT3NGWjAwZllkNkRBcC95YWY3QXJ1N3Bha3BpRzBU
            YUc1dTdQekhNVWJrZllYeEhMcXdEYnN6TXZzM0ZmVE1XWFdzVkVYUHdiUXE4ZE9X
            aFkzcVVRNm40TnNPWVRFQnYrVVhvNXE5NWZOeXRvN0VCV2ZmMm9mdDVqdmFlU0c0
            bC9OQ0RPUC9WT0hEUjRFNTdlUWZRYVZVRTAwTDNwN2VQUVhuVTBwUHRCWDBuUXBu
            SWxOYTVVQ3AwcW5IQXdmYjh3aXU4ZjNvdXJXWmZxOXpRc3pESkdyeVRzaHhMR2tJ
            MG96S2VSaXp4Q1MyUjlBancwYml3ay81WGltNzVRZVZsVUpkNjBxeklzOTl0WlFV
            YUpaQk9LTVR0Nm53cEFac1JnN0pHaFc1SE9sSmNiaDlMdHE2Y25QS1l0a0h1V2t3
            TDFjT0hsMEo1WVIwaWYrYjhzQm12cGlIUHpodE5DSUtBdmVnN3FackFaak1GaHB1
            Z0hKblBzSmNrSkVmdi9OMkVFTHZ1ZForSm9PNUd5UU0zdldtKytVZU1mZllXZwpi
            UEFPb0Y0MzNSUHFYRnBZY1RHd2I0Si9qWStQR2ZyVWNlUUlJcDRNVUZVCi0tLSBX
            R2VpTko4d0JRd0NBMitGeWpFN2owM3k0RUhsYmpKeUN0MEk5SDhtY000CgmZbm3j
            JRY0JoiOsr0IXxkyBAJm6+Wx1qGUGZXnJOvZyFALq8vVJNeJrWED5NV1dUHDYuLI
            dZMAzOYDvD7ux9A=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1txa5jfq4y6xn2w6aj778jkyu8wsm47ke0pt05jm4dgmhj7chenqcnr0rq47y2sm4kacyp49w9wcyyc7z29luwrlvjcd0y7n7urnjkvheqx3nyl0xpvvwhdw0vkahpd5e9c8ctn7ej68y93z56eq4tw0cg92425tsmrr4t3frkwkyrv2t59ldwnsscwhqwqxtyv6q6gvrfj2trrclscvjd4plcsrtj8vhq9cc0f0sujwd5vuum59rnaxc4se0sh9uq223ln9n0hyt29m3578he24urp625k6wnmgkgmsncnamccy48wleaxzqrsnc463rstpgc7s3n3mu35457aasshr8n43s290f2s92kqps2n969h8g0djexymceqlqvq5ctrp68a9m5k0x5chxhqr7a7tr55n4r3wcynnwdyyehpxxp2ap25yt6hxqxkphtveyagd8wsa0dkah4mluj7nhd2ddlxne689h9euk6smsj8yfhda8kr8lw72vgjckwhzeeqxspxftgpuyr79q52ajdh0kz6duf2xlx4tr35z9ntfj3arzq4jehz0yjwrqwecsk4469x8p94ekswhfhp8mxagceaehgytvntn7nz6zeg832rp5vznmxndv5avc2ttlhgxuqvpssk4x3gl2xw80ksgz0gzru4d8gz3jlue82wtgk2pvhswle42ldecnrnx5klmhf0nsgywhkanzajpsg8dkgvf5yxgfjqeu5xn06vnmvepvfdkr5jand3ja3uz9axut35jvp85xjkrzlxtz5wvl29zqfkc8yxwujykx6v23njd33cufge9h0nt5400glvrfndd4hjfvvywh8rlq39lwl9f5yuc66n4v2ufzq0sgzrnmtz92dstfv93f59ymt5a33ds8kxst5997teu5hj8tqwuzk73z5wepcgsqys9ql7sjn5p9z9l2xft8s5zryrz6sstvxuj34p9jm36vsy5sj3z3ec7q8sg4chkeddy43qkqcaf5ave58xq40zngh9y55vjz7du4dtfcddxatwtm3p6pzxpepftqd8pkjmmughhxhdq7e6pealyv9gj6w5ps2tqx24kk7l9kl3zjlemvkvk38qgfva4wfpnjemjfjdjyzmc2sn88e3afz6553gstpffm0uu7d3gfwwm72fd7ezx9sxhffdrrnvymuknugepms79m6pyhjyp7ye366jrp59da07ufgcc6kyfdx26mgnqq74cdzqdr824vzx0vdff0gm8mnpudgmfxnz4r5yue5pln54m0pw542858frvhr30v5xt77cqh0qa29anyt7xuhchx40pf6d7mcz44nerpn5qq4g35qc7ad9kyma5uwrqenythpa7txkns5e5lu8yhuumnlu88yv8zssm5npku5af08tasfmy8kpm483jyddzkeve7asqsxw6x00ra3wg7rqhzu5zr8pykcf03c8cu3w48t2sd72wzffsky93pkwfw3jnmuc78me6t7hfg08ruxnp5xwz56q4f7evl6zuukgnxfrpqyk4aqaq0f7rdhlrfphume8tftsgn8ynjt7rgsgfgas5spn3s4nzrgp7ajurfj678h0d60p3l48e62eeps7q5n6m6n5mxw7mdr9a3sckkah9lctv33zfzvt48v4m4wjxqpywvgcdqs4cx9fedzm8klzkvussp5emv9zv4g3v68tgvfp57ap335kf8sq58h93e3tghudem0vzerqts5pxfel59k5gftsr4cxempk98uumjjdyc8pcwljflyftc6ne6a8lr4gumvtk77yyj9espzlskx5dz8prn38wn5xqfwy3xhjzx8xps5tdckxhaejy9mfjavjhrj68wwwzx809zgkckn63dsg2jqg85h3hnwnpw9rm8jy5udzd62ej52ycwkv7ejwsm6dr4zcavgsua
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZFppQVpaOFF0b3lRRDlW
            T05OK3p2Q05iU01ySVJMSVA0ZjFlSTdLSWtFCmtsaEY0aE12ejBEaTBCSzlZK2xa
            V1g1dHd6Y0lVRUdWV2xNczhsSE5adTgKLS0tIEdubWI3UWxhb0lwaVFMbGZDTVhU
            cDk1N3VZZTJvRlZFNDdjV3dvdFpUVTQKd/rZRIgW1/00TV6cHMfJWp8/k/MwW1Rd
            uFsgaQfn3WU4+JIYAqId2eWaUVGU8KxafDPDrlU2qvRuizxa3IM2MQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dtwmd5txsdjh3agr7zlqum8h024hasarflnpfavyqsu7g2lvvyksv8zff5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNk1qRm9OSjREVDdhUjdU
            djl2bXVMQnJYVUU1VDAyeVBRbGN1eExlZkJNCjlqOE9GQ0h0d2NrTndKTFJYTW42
            aGpFVDJvR3NlUEs4aGlGYXV6ZFV6NU0KLS0tIEJxUVpIMEgyKzZaYzlZcys3bTFr
            bDkxRU9weUkxWjdJUVpLQ05CR2pKU1UKBohBL/mGhwxjg1+j+28tUPPKYgMvckva
            PTaz9m3whhgweqYuF9IQ4e83GZL3aakfKmbNsy2Vhag8BDD4vedxTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ns0hnk5n6sw9uqdn7v4rynumjk0zd8zfsjhegka74xw55nnluy4qtju5um
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bWtyalAzNC9waTgzcm1F
            WWtaQUdVVGQ1TFpodUxXNlpSZnZnaWdKd0R3CjBQSW4rMXFLZ1gySVpmVFAwY3Vk
            eVpKZHNzekdLeVVWVmFPaDZ5NFlCVHcKLS0tIDQwV0dWeldGSmZjUGtYalhGTkpw
            UVpoc0V5K3R4djRyMms2RUFVaU9lYjQK2DjrlEXP2gsfvt+63X0kgOo3QxechC0h
            mwpqESW/06/g42ZDMgllzBwEw6gdrijPCIQMncbqaQu7Pcc+TJglOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10w46rzpkfyx7cfx8hy6dq059cw8zy7mrvtu2gc06hngyxspeh9aq45ssty
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTzBhMTJsNUUwQ3QzaCt5
            c2pYbHRwbHAwQS81Y1FTNWVmTGM2YU4rREVvCjBRK3FWdldwYW1EbHlycGJlTERo
            M3dzT1NMWGpidytmWmhUNmNSV2RXQ2MKLS0tIE9ob2lwaXphUmRPRkthbmt1M3Fv
            TDZnSWZlaHBkRHRCNCtTUUY1VUtwdHMKi9fPIPuobuNfS154Edg5aWOGV7av2XQm
            yvijcGch2hZZ8kh2C6XtngJ0Pi4gEHwIiF7kzzzz0qxPPxVN3OBZmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f67pujrh0ejw4a0540wmjs6jhxwdpkyvw798nnm5c6smfgmw99yqs34n2s
    lastmodified: "2026-08-18T10:50:17Z"
    mac: ENC[AES256_GCM,data:eUfILm3FctObV5wZtIxfilhD8fmOjwh3Tp41BULcoss6wpxa7ZPzyp0krthFZ4MU+TBBR4D9/yztUggakDhkReWsYuNsAtxq24RMPwDtdI2JoFT7RAL2AlqXGneonYa4ePDE+K2/Hv4SpiLyc0cqqjHO8Z9vOXZeRMv+PgnplcQ=,iv:X08O8ogvjIg5J3UawbYhNTerccVU9YInLAT4LVsC2go=,tag:vZ4mTEZcz7mAKNsyjy520w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
