#!/usr/bin/env zsh

if [[ ! -f /usr/lib/systemd/user/gpg-agent.socket ]]; then
  # well we're on an older system without the systemd services

  # use a tty for gpg
  # solves error: "gpg: signing failed: Inappropriate ioctl for device"
  GPG_TTY=$(tty)
  export GPG_TTY

  # add alias for ssh to update the tty
  #alias ssh="gpg-connect-agent updatestartuptty /bye >/dev/null; ssh"
  gpgconf --launch gpg-agent
fi
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

function compile-ssh-config() {
    >~/.ssh/config cat <<EOF
# --* This file is automatically generated and overwritten by .zlogin. *--
# --* Put configuration into a file in ~/.ssh/config.d instead. *--
EOF
    for file in ~/.ssh/config.d/*; do
        printf "\n# --- $file ---\n" >> ~/.ssh/config
        #sed 's;\$(XDG_CACHE_HOME|\{XDG_CACHE_HOME\});'"${XDG_CACHE_HOME};" $file >> ~/.ssh/config
        #cat $file >> ~/.ssh/config
        sed "s;\$XDG_CACHE_HOME;${XDG_CACHE_HOME};" $file >> ~/.ssh/config
    done
}
