{
  config,
  ...
}:
let
  inherit (config.modules.users.primaryUser) username;
in
{
  # KDE Plasma has a large number of separate dotfiles
  # so keep them separate from the main persisted home dotfiles.
  environment.persistence."/persist/kde-dotfiles" = {
    hideMounts = true;
    users.${username} = {
      directories = [
        ".cache/digikam"
        ".config/gtk-3.0" # fuse mounted
        ".config/gtk-4.0" # to /home/$USERNAME/.config/gtk-3.0
        ".config/KDE"
        ".config/kde.org"
        ".config/plasma-workspace"
        ".config/xsettingsd"
        ".kde"
        ".local/share/baloo"
        ".local/share/digikam"
        ".local/share/dolphin"
        ".local/share/gwenview"
        ".local/share/kactivitymanagerd"
        ".local/share/kate"
        ".local/share/klipper"
        ".local/share/konsole"
        ".local/share/kscreen"
        ".local/share/kwalletd"
        ".local/share/kxmlgui5"
        ".local/share/okular"
        ".local/share/RecentDocuments"
        ".local/share/sddm"
      ];
      files = [
        ".config/akregatorrc"
        ".config/baloofileinformationrc"
        ".config/baloofilerc"
        ".config/bluedevilglobalrc"
        ".config/device_automounter_kcmrc"
        ".config/dolphinrc"
        ".config/filetypesrc"
        ".config/gtkrc"
        ".config/gtkrc-2.0"
        ".config/gwenviewrc"
        ".config/kactivitymanagerd-pluginsrc"
        ".config/kactivitymanagerd-statsrc"
        ".config/kactivitymanagerd-switcher"
        ".config/kactivitymanagerdrc"
        ".config/katemetainfos"
        ".config/katerc"
        ".config/kateschemarc"
        ".config/katevirc"
        ".config/kcmfonts"
        ".config/kcminputrc"
        ".config/kconf_updaterc"
        ".config/kded5rc"
        ".config/kdeglobals"
        ".config/kgammarc"
        ".config/kglobalshortcutsrc"
        ".config/khotkeysrc"
        ".config/kmixrc"
        ".config/konsolerc"
        ".config/kscreenlockerrc"
        ".config/ksmserverrc"
        ".config/ksplashrc"
        ".config/ktimezonedrc"
        ".config/kwinrc"
        ".config/kwinrulesrc"
        ".config/kxkbrc"
        ".config/mimeapps.list"
        ".config/partitionmanagerrc"
        ".config/plasma-localerc"
        ".config/plasma-nm"
        ".config/plasma-org.kde.plasma.desktop-appletsrc"
        ".config/plasmanotifyrc"
        ".config/plasmarc"
        ".config/plasmashellrc"
        ".config/PlasmaUserFeedback"
        ".config/plasmawindowed-appletsrc"
        ".config/plasmawindowedrc"
        ".config/powermanagementprofilesrc"
        ".config/spectaclerc"
        ".config/startkderc"
        ".config/systemsettingsrc"
        ".config/Trolltech.conf"
        ".config/user-dirs.locale"
        ".local/share/krunnerstaterc"
        ".local/share/user-places.xbel"
        ".local/share/user-places.xbel.bak"
        ".local/share/user-places.xbel.tbcache"
      ];
    };
  };
  environment.persistence."/persist" = {
    directories = [
      "/var/lib/nixos"
      "/var/lib/systemd/coredump"
    ];
    users.${username} = {
      directories = [
        "nixcfg"
        "nixcfg-private"
        "docs"
        "downloads"
        "src"
        "sync"
        "vendor"
        "work"
        ".local/state"
        ".cache/nix"
        ".cache/pi-web"
        ".cache/audacity"
        ".cache/gimp"
        ".cache/inkscape"
        ".cache/virt-manager"
        ".config/hacompanion"
        ".config/pi-web"
        ".config/audacity"
        ".config/easyeffects"
        ".config/GIMP"
        ".config/gnupg"
        ".config/hcloud"
        ".config/inkscape"
        ".config/fly"
        ".config/autostart"
        ".config/PrusaSlicer"
        ".config/PrusaSlicer-alpha"
        ".config/qobuz-dl"
        ".config/rclone"
        ".config/waytray"
        ".config/Zeal"
        ".config/libro-fm-cli"
        ".config/audiobookshelf-cli"
        ".config/paperless-cli"
        ".config/invoiceninja-cli"
        ".local/bin"
        ".local/share/keyrings"
        ".local/share/audacity"
        ".local/share/fonts"
        ".local/share/krita"
        ".local/share/pi-web"
        ".local/share/npm"
        ".local/share/Zeal"
        ".config/adept"
        ".config/pi-matrix-relay"
        ".config/nixbot-cli"
        ".local/state/pi-matrix-relay"
        ".config/warp-terminal"
        ".config/libreoffice"
        ".config/qt5ct"
        ".config/qt6ct"
        ".local/share/Libation"
        ".sprites"
      ];
      files = [
        ".local/share/recently-used.xbel"
      ];
    };
  };
}
