{
 "title": "zrepl1",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "prom_job_name",
    "label": "Prometheus Job Name",
    "query": {
     "query": "label_values(zrepl_start_time,job)"
    }
   },
   {
    "name": "zrepl_replication_jobid",
    "query": {
     "query": "label_values(zrepl_replication_filesystem_errors{job=\"$prom_job_name\"},zrepl_job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "About",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# zrepl Prometheus Metrics\n\nzrepl exposes Prometheus metrics and ships with this Grafana dashboard.\nThe exported metrics are suitable for health checks:\n\n* The log should generally be warning & error-free\n  * The `Log Messages that require attention` graph visualizes log message at levels that generally indicate problems.\n* In most setups, there shouldn't be any unmatched filesystem filter rules.\n* The number of goroutines should not grow unboundedly over time.\n  * During replication, the number of goroutines can be way higher than during idle time.\n  * If the goroutine count grows with each replication, there is clearly a goroutine leak. Please open a bug report.\n* Memory consumption should not grow unboundedly over time.\n  * Note that the Go runtime pre-allocates some of its heap from the OS.\n  * zrepl actually uses much less memory than allocated from the OS.\n  * Since Go 1.11, Go pre-allocates more aggressively.\n* Monitor that some data is replicated, although that metric does not guarantee that replication was successful.\n\n**In general, note that the exported metrics are not stable unless declared otherwise.**"
     }
    }
   ]
  },
  { "title": "Top", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "zrepl Instances running",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sgn(zrepl_start_time{job='$prom_job_name'})",
     "legendFormat": "{{instance}}@version={{raw}}"
    }
   ]
  },
  {
   "title": "Log events by zrepl job",
   "type": "timeseries",
   "description": "zrepl maintains event counters for each `job x log_level`, independent of the logging outlet configuration in the config.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(zrepl_daemon_log_entries{job=\"$prom_job_name\"}[$__rate_interval])) by (instance,zrepl_job)"
    }
   ]
  },
  {
   "title": "Log Messages that require attention",
   "type": "timeseries",
   "description": "A functioning setup should not be logging `warn` / `error` messages.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(zrepl_daemon_log_entries{job='$prom_job_name',level=~'warn|error'}[$__rate_interval]) > 0"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Replication jobs Filesystems with failed replications.",
   "type": "status-history",
   "description": "Number of filesystems that failed replications.\nGauge is updated after the invocation has finished and remains at the resulting value until it is updated at the end of the next invocation.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance,job,zrepl_job) (zrepl_replication_filesystem_errors{job=\"$prom_job_name\",zrepl_job=~\"$zrepl_replication_jobid\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Replication Data Volume",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(zrepl_replication_bytes_replicated{job='$prom_job_name'}[1d])) by (zrepl_job)",
     "legendFormat": "zrepl_job={{zrepl_job}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 19 },
   "options": {
    "content": "### Unmatched Filesystems Rules\n\nFilesystem filter rules which mention datasets that didn't exist in the `zfs list` output."
   }
  },
  {
   "title": "Occurences [Dashboard Range]",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 19 },
   "targets": [
    {
     "expr": "increase(zrepl_zfs_list_unmatched_user_specified_dataset_count{job=\"$prom_job_name\",jobid=~\"$zrepl_replication_jobid\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Data Rate and Volume(over last 10min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(zrepl_replication_bytes_replicated{job='$prom_job_name'}[10m])) by (zrepl_job)",
     "legendFormat": "replication data ratein last 10min zrepl_job={{zrepl_job}}te zrepl_job={{zrepl_job}}"
    },
    {
     "expr": "sum(increase(zrepl_replication_bytes_replicated{job='$prom_job_name'}[10m])) by (zrepl_job)",
     "legendFormat": "replicated bytes in last 10min zrepl_job={{zrepl_job}}"
    }
   ]
  },
  {
   "title": "Occurences increase[$__interval]",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "increase(zrepl_zfs_list_unmatched_user_specified_dataset_count{job=\"$prom_job_name\",jobid=\"$zrepl_replication_jobid\"}[$__interval])",
     "legendFormat": "{{jobid}}"
    }
   ]
  },
  { "title": "Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "active tasks tracked by the zrepl trace module (should not grow unboundedly)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "zrepl_trace_active_tasks{job=\"$prom_job_name\"}"
    }
   ]
  },
  {
   "title": "number of goroutines (should not grow unboundedly)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "go_goroutines{job='$prom_job_name'}"
    }
   ]
  },
  {
   "title": "Memory Allocated by the Go runtime from the OS (should not grow unboundedly)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job='$prom_job_name'}"
    }
   ]
  },
  {
   "title": "Go Memory Allocations (should not grow unboundedly)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job='$prom_job_name'}"
    }
   ]
  },
  {
   "title": "zfs abstractions cache entry count (should not be zero and not grow unboundedly)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "zrepl_endpoint_abstractions_cache_entry_count"
    }
   ]
  }
 ]
}